// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
	"openapi/internal/sdk/sdkinternal/utils"
)

// Item - Object with `id` plus the same property body shape as PATCH (`default`/`list`/`extended`).
type Item struct {
	ID                   string         `json:"id"`
	AdditionalProperties map[string]any `additionalProperties:"true" json:"-"`
}

func (i Item) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *Item) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *Item) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *Item) GetAdditionalProperties() map[string]any {
	if i == nil {
		return nil
	}
	return i.AdditionalProperties
}

type BatchUpdateObjectsRequestBody struct {
	Items []Item `json:"items"`
}

func (b *BatchUpdateObjectsRequestBody) GetItems() []Item {
	if b == nil {
		return []Item{}
	}
	return b.Items
}

type BatchUpdateObjectsRequest struct {
	TeamID     string                `pathParam:"style=simple,explode=false,name=teamId"`
	ObjectType components.ObjectType `pathParam:"style=simple,explode=false,name=objectType"`
	// A unique key (UUID or any opaque string up to 255 chars) that identifies this logical request. The server caches the first response under this key for 24 hours and replays it on retry — safe to use on every POST/PUT/PATCH to make network retries deterministic. Reusing the same key with a different body returns 409 `idempotency_key_mismatch`. Replays include the `idempotent-replay: true` response header.
	IdempotencyKey *string                       `header:"style=simple,explode=false,name=Idempotency-Key"`
	Body           BatchUpdateObjectsRequestBody `request:"mediaType=application/json"`
}

func (b *BatchUpdateObjectsRequest) GetTeamID() string {
	if b == nil {
		return ""
	}
	return b.TeamID
}

func (b *BatchUpdateObjectsRequest) GetObjectType() components.ObjectType {
	if b == nil {
		return components.ObjectType("")
	}
	return b.ObjectType
}

func (b *BatchUpdateObjectsRequest) GetIdempotencyKey() *string {
	if b == nil {
		return nil
	}
	return b.IdempotencyKey
}

func (b *BatchUpdateObjectsRequest) GetBody() BatchUpdateObjectsRequestBody {
	if b == nil {
		return BatchUpdateObjectsRequestBody{}
	}
	return b.Body
}

type BatchUpdateObjectsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Per-item outcomes
	BatchResult *components.BatchResult
	Headers     map[string][]string
}

func (b BatchUpdateObjectsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BatchUpdateObjectsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BatchUpdateObjectsResponse) GetHTTPMeta() components.HTTPMetadata {
	if b == nil {
		return components.HTTPMetadata{}
	}
	return b.HTTPMeta
}

func (b *BatchUpdateObjectsResponse) GetBatchResult() *components.BatchResult {
	if b == nil {
		return nil
	}
	return b.BatchResult
}

func (b *BatchUpdateObjectsResponse) GetHeaders() map[string][]string {
	if b == nil {
		return map[string][]string{}
	}
	return b.Headers
}
