// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
	"openapi/internal/sdk/sdkinternal/utils"
)

type BatchDeleteObjectsRequestBody struct {
	Ids []string `json:"ids"`
}

func (b *BatchDeleteObjectsRequestBody) GetIds() []string {
	if b == nil {
		return []string{}
	}
	return b.Ids
}

type BatchDeleteObjectsRequest struct {
	TeamID     string                `pathParam:"style=simple,explode=false,name=teamId"`
	ObjectType components.ObjectType `pathParam:"style=simple,explode=false,name=objectType"`
	// A unique key (UUID or any opaque string up to 255 chars) that identifies this logical request. The server caches the first response under this key for 24 hours and replays it on retry — safe to use on every POST/PUT/PATCH to make network retries deterministic. Reusing the same key with a different body returns 409 `idempotency_key_mismatch`. Replays include the `idempotent-replay: true` response header.
	IdempotencyKey *string                       `header:"style=simple,explode=false,name=Idempotency-Key"`
	Body           BatchDeleteObjectsRequestBody `request:"mediaType=application/json"`
}

func (b *BatchDeleteObjectsRequest) GetTeamID() string {
	if b == nil {
		return ""
	}
	return b.TeamID
}

func (b *BatchDeleteObjectsRequest) GetObjectType() components.ObjectType {
	if b == nil {
		return components.ObjectType("")
	}
	return b.ObjectType
}

func (b *BatchDeleteObjectsRequest) GetIdempotencyKey() *string {
	if b == nil {
		return nil
	}
	return b.IdempotencyKey
}

func (b *BatchDeleteObjectsRequest) GetBody() BatchDeleteObjectsRequestBody {
	if b == nil {
		return BatchDeleteObjectsRequestBody{}
	}
	return b.Body
}

type BatchDeleteObjectsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Per-item outcomes
	BatchResult *components.BatchResult
	Headers     map[string][]string
}

func (b BatchDeleteObjectsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BatchDeleteObjectsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BatchDeleteObjectsResponse) GetHTTPMeta() components.HTTPMetadata {
	if b == nil {
		return components.HTTPMetadata{}
	}
	return b.HTTPMeta
}

func (b *BatchDeleteObjectsResponse) GetBatchResult() *components.BatchResult {
	if b == nil {
		return nil
	}
	return b.BatchResult
}

func (b *BatchDeleteObjectsResponse) GetHeaders() map[string][]string {
	if b == nil {
		return map[string][]string{}
	}
	return b.Headers
}
