// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
	"openapi/internal/sdk/sdkinternal/utils"
)

type CountObjectsRequest struct {
	TeamID     string                `pathParam:"style=simple,explode=false,name=teamId"`
	ObjectType components.ObjectType `pathParam:"style=simple,explode=false,name=objectType"`
	// Scope the count to a specific list/app.
	ListID *string `queryParam:"style=form,explode=true,name=list_id"`
}

func (c *CountObjectsRequest) GetTeamID() string {
	if c == nil {
		return ""
	}
	return c.TeamID
}

func (c *CountObjectsRequest) GetObjectType() components.ObjectType {
	if c == nil {
		return components.ObjectType("")
	}
	return c.ObjectType
}

func (c *CountObjectsRequest) GetListID() *string {
	if c == nil {
		return nil
	}
	return c.ListID
}

// CountObjectsResponseBody - OK
type CountObjectsResponseBody struct {
	// Number of records matching the access scope.
	Total int64 `json:"total"`
}

func (c *CountObjectsResponseBody) GetTotal() int64 {
	if c == nil {
		return 0
	}
	return c.Total
}

type CountObjectsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Object  *CountObjectsResponseBody
	Headers map[string][]string
}

func (c CountObjectsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CountObjectsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CountObjectsResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CountObjectsResponse) GetObject() *CountObjectsResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}

func (c *CountObjectsResponse) GetHeaders() map[string][]string {
	if c == nil {
		return map[string][]string{}
	}
	return c.Headers
}
