// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
	"openapi/internal/sdk/sdkinternal/utils"
)

type CreateMetadataPropertyRequest struct {
	TeamID     string                `pathParam:"style=simple,explode=false,name=teamId"`
	ObjectType components.ObjectType `pathParam:"style=simple,explode=false,name=objectType"`
	// A unique key (UUID or any opaque string up to 255 chars) that identifies this logical request. The server caches the first response under this key for 24 hours and replays it on retry — safe to use on every POST/PUT/PATCH to make network retries deterministic. Reusing the same key with a different body returns 409 `idempotency_key_mismatch`. Replays include the `idempotent-replay: true` response header.
	IdempotencyKey *string                             `header:"style=simple,explode=false,name=Idempotency-Key"`
	Body           components.PropertyDefinitionCreate `request:"mediaType=application/json"`
}

func (c *CreateMetadataPropertyRequest) GetTeamID() string {
	if c == nil {
		return ""
	}
	return c.TeamID
}

func (c *CreateMetadataPropertyRequest) GetObjectType() components.ObjectType {
	if c == nil {
		return components.ObjectType("")
	}
	return c.ObjectType
}

func (c *CreateMetadataPropertyRequest) GetIdempotencyKey() *string {
	if c == nil {
		return nil
	}
	return c.IdempotencyKey
}

func (c *CreateMetadataPropertyRequest) GetBody() components.PropertyDefinitionCreate {
	if c == nil {
		return components.PropertyDefinitionCreate{}
	}
	return c.Body
}

type CreateMetadataPropertyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Property created
	PropertyDefinition *components.PropertyDefinition
	Headers            map[string][]string
}

func (c CreateMetadataPropertyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateMetadataPropertyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateMetadataPropertyResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateMetadataPropertyResponse) GetPropertyDefinition() *components.PropertyDefinition {
	if c == nil {
		return nil
	}
	return c.PropertyDefinition
}

func (c *CreateMetadataPropertyResponse) GetHeaders() map[string][]string {
	if c == nil {
		return map[string][]string{}
	}
	return c.Headers
}
