// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
	"openapi/internal/sdk/sdkinternal/utils"
)

type CreateViewRequest struct {
	TeamID         string                    `pathParam:"style=simple,explode=false,name=teamId"`
	ViewObjectType components.ViewObjectType `pathParam:"style=simple,explode=false,name=viewObjectType"`
	// A unique key (UUID or any opaque string up to 255 chars) that identifies this logical request. The server caches the first response under this key for 24 hours and replays it on retry — safe to use on every POST/PUT/PATCH to make network retries deterministic. Reusing the same key with a different body returns 409 `idempotency_key_mismatch`. Replays include the `idempotent-replay: true` response header.
	IdempotencyKey *string               `header:"style=simple,explode=false,name=Idempotency-Key"`
	Body           components.ViewBundle `request:"mediaType=application/json"`
}

func (c *CreateViewRequest) GetTeamID() string {
	if c == nil {
		return ""
	}
	return c.TeamID
}

func (c *CreateViewRequest) GetViewObjectType() components.ViewObjectType {
	if c == nil {
		return components.ViewObjectType("")
	}
	return c.ViewObjectType
}

func (c *CreateViewRequest) GetIdempotencyKey() *string {
	if c == nil {
		return nil
	}
	return c.IdempotencyKey
}

func (c *CreateViewRequest) GetBody() components.ViewBundle {
	if c == nil {
		return components.ViewBundle{}
	}
	return c.Body
}

type CreateViewResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	ViewBundle *components.ViewBundle
	Headers    map[string][]string
}

func (c CreateViewResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateViewResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateViewResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateViewResponse) GetViewBundle() *components.ViewBundle {
	if c == nil {
		return nil
	}
	return c.ViewBundle
}

func (c *CreateViewResponse) GetHeaders() map[string][]string {
	if c == nil {
		return map[string][]string{}
	}
	return c.Headers
}
