// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
	"openapi/internal/sdk/sdkinternal/utils"
)

type CreateObjectRequest struct {
	TeamID     string                `pathParam:"style=simple,explode=false,name=teamId"`
	ObjectType components.ObjectType `pathParam:"style=simple,explode=false,name=objectType"`
	// A unique key (UUID or any opaque string up to 255 chars) that identifies this logical request. The server caches the first response under this key for 24 hours and replays it on retry — safe to use on every POST/PUT/PATCH to make network retries deterministic. Reusing the same key with a different body returns 409 `idempotency_key_mismatch`. Replays include the `idempotent-replay: true` response header.
	IdempotencyKey *string                               `header:"style=simple,explode=false,name=Idempotency-Key"`
	Body           components.PrismObjectPropertiesUnion `request:"mediaType=application/json"`
}

func (c *CreateObjectRequest) GetTeamID() string {
	if c == nil {
		return ""
	}
	return c.TeamID
}

func (c *CreateObjectRequest) GetObjectType() components.ObjectType {
	if c == nil {
		return components.ObjectType("")
	}
	return c.ObjectType
}

func (c *CreateObjectRequest) GetIdempotencyKey() *string {
	if c == nil {
		return nil
	}
	return c.IdempotencyKey
}

func (c *CreateObjectRequest) GetBody() components.PrismObjectPropertiesUnion {
	if c == nil {
		return components.PrismObjectPropertiesUnion{}
	}
	return c.Body
}

type CreateObjectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Object created
	PrismObjectResponse *components.PrismObjectResponse
	Headers             map[string][]string
}

func (c CreateObjectResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateObjectResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateObjectResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateObjectResponse) GetPrismObjectResponse() *components.PrismObjectResponse {
	if c == nil {
		return nil
	}
	return c.PrismObjectResponse
}

func (c *CreateObjectResponse) GetHeaders() map[string][]string {
	if c == nil {
		return map[string][]string{}
	}
	return c.Headers
}
