// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
	"openapi/internal/sdk/sdkinternal/utils"
)

type CreateMetadataPropertyOptionRequest struct {
	TeamID     string                `pathParam:"style=simple,explode=false,name=teamId"`
	ObjectType components.ObjectType `pathParam:"style=simple,explode=false,name=objectType"`
	PropertyID string                `pathParam:"style=simple,explode=false,name=propertyId"`
	// A unique key (UUID or any opaque string up to 255 chars) that identifies this logical request. The server caches the first response under this key for 24 hours and replays it on retry — safe to use on every POST/PUT/PATCH to make network retries deterministic. Reusing the same key with a different body returns 409 `idempotency_key_mismatch`. Replays include the `idempotent-replay: true` response header.
	IdempotencyKey *string                         `header:"style=simple,explode=false,name=Idempotency-Key"`
	Body           components.PropertyOptionCreate `request:"mediaType=application/json"`
}

func (c *CreateMetadataPropertyOptionRequest) GetTeamID() string {
	if c == nil {
		return ""
	}
	return c.TeamID
}

func (c *CreateMetadataPropertyOptionRequest) GetObjectType() components.ObjectType {
	if c == nil {
		return components.ObjectType("")
	}
	return c.ObjectType
}

func (c *CreateMetadataPropertyOptionRequest) GetPropertyID() string {
	if c == nil {
		return ""
	}
	return c.PropertyID
}

func (c *CreateMetadataPropertyOptionRequest) GetIdempotencyKey() *string {
	if c == nil {
		return nil
	}
	return c.IdempotencyKey
}

func (c *CreateMetadataPropertyOptionRequest) GetBody() components.PropertyOptionCreate {
	if c == nil {
		return components.PropertyOptionCreate{}
	}
	return c.Body
}

type CreateMetadataPropertyOptionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Option created
	PropertyOption *components.PropertyOption
	Headers        map[string][]string
}

func (c CreateMetadataPropertyOptionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateMetadataPropertyOptionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateMetadataPropertyOptionResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateMetadataPropertyOptionResponse) GetPropertyOption() *components.PropertyOption {
	if c == nil {
		return nil
	}
	return c.PropertyOption
}

func (c *CreateMetadataPropertyOptionResponse) GetHeaders() map[string][]string {
	if c == nil {
		return map[string][]string{}
	}
	return c.Headers
}
