// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
)

type DeleteObjectRequest struct {
	TeamID     string                `pathParam:"style=simple,explode=false,name=teamId"`
	ObjectType components.ObjectType `pathParam:"style=simple,explode=false,name=objectType"`
	ObjectID   string                `pathParam:"style=simple,explode=false,name=objectId"`
	// Optimistic concurrency. Pass back the `etag` header from a previous GET of this record; the write only proceeds if the record hasn't changed since. Mismatch → 412 `precondition_failed`. Use `*` to require the record exists (any ETag accepted).
	IfMatch *string `header:"style=simple,explode=false,name=If-Match"`
}

func (d *DeleteObjectRequest) GetTeamID() string {
	if d == nil {
		return ""
	}
	return d.TeamID
}

func (d *DeleteObjectRequest) GetObjectType() components.ObjectType {
	if d == nil {
		return components.ObjectType("")
	}
	return d.ObjectType
}

func (d *DeleteObjectRequest) GetObjectID() string {
	if d == nil {
		return ""
	}
	return d.ObjectID
}

func (d *DeleteObjectRequest) GetIfMatch() *string {
	if d == nil {
		return nil
	}
	return d.IfMatch
}

type DeleteObjectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Headers  map[string][]string
}

func (d *DeleteObjectResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteObjectResponse) GetHeaders() map[string][]string {
	if d == nil {
		return map[string][]string{}
	}
	return d.Headers
}
