// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
)

type DeleteMetadataPropertyRequest struct {
	TeamID     string                `pathParam:"style=simple,explode=false,name=teamId"`
	ObjectType components.ObjectType `pathParam:"style=simple,explode=false,name=objectType"`
	PropertyID string                `pathParam:"style=simple,explode=false,name=propertyId"`
	// Storage type of this property definition.
	Type   components.PropertyType `queryParam:"style=form,explode=true,name=type"`
	ListID *string                 `queryParam:"style=form,explode=true,name=list_id"`
}

func (d *DeleteMetadataPropertyRequest) GetTeamID() string {
	if d == nil {
		return ""
	}
	return d.TeamID
}

func (d *DeleteMetadataPropertyRequest) GetObjectType() components.ObjectType {
	if d == nil {
		return components.ObjectType("")
	}
	return d.ObjectType
}

func (d *DeleteMetadataPropertyRequest) GetPropertyID() string {
	if d == nil {
		return ""
	}
	return d.PropertyID
}

func (d *DeleteMetadataPropertyRequest) GetType() components.PropertyType {
	if d == nil {
		return components.PropertyType("")
	}
	return d.Type
}

func (d *DeleteMetadataPropertyRequest) GetListID() *string {
	if d == nil {
		return nil
	}
	return d.ListID
}

type DeleteMetadataPropertyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Headers  map[string][]string
}

func (d *DeleteMetadataPropertyResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteMetadataPropertyResponse) GetHeaders() map[string][]string {
	if d == nil {
		return map[string][]string{}
	}
	return d.Headers
}
