// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
)

type DeleteViewRequest struct {
	TeamID         string                    `pathParam:"style=simple,explode=false,name=teamId"`
	ViewObjectType components.ViewObjectType `pathParam:"style=simple,explode=false,name=viewObjectType"`
	ViewID         string                    `pathParam:"style=simple,explode=false,name=viewId"`
}

func (d *DeleteViewRequest) GetTeamID() string {
	if d == nil {
		return ""
	}
	return d.TeamID
}

func (d *DeleteViewRequest) GetViewObjectType() components.ViewObjectType {
	if d == nil {
		return components.ViewObjectType("")
	}
	return d.ViewObjectType
}

func (d *DeleteViewRequest) GetViewID() string {
	if d == nil {
		return ""
	}
	return d.ViewID
}

type DeleteViewResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Headers  map[string][]string
}

func (d *DeleteViewResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteViewResponse) GetHeaders() map[string][]string {
	if d == nil {
		return map[string][]string{}
	}
	return d.Headers
}
