// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
)

type DeleteMetadataPropertyOptionRequest struct {
	TeamID     string                `pathParam:"style=simple,explode=false,name=teamId"`
	ObjectType components.ObjectType `pathParam:"style=simple,explode=false,name=objectType"`
	PropertyID string                `pathParam:"style=simple,explode=false,name=propertyId"`
	OptionID   string                `pathParam:"style=simple,explode=false,name=optionId"`
	// Storage type for a property definition.
	Type   components.PropertyType `queryParam:"style=form,explode=true,name=type"`
	ListID *string                 `queryParam:"style=form,explode=true,name=list_id"`
}

func (d *DeleteMetadataPropertyOptionRequest) GetTeamID() string {
	if d == nil {
		return ""
	}
	return d.TeamID
}

func (d *DeleteMetadataPropertyOptionRequest) GetObjectType() components.ObjectType {
	if d == nil {
		return components.ObjectType("")
	}
	return d.ObjectType
}

func (d *DeleteMetadataPropertyOptionRequest) GetPropertyID() string {
	if d == nil {
		return ""
	}
	return d.PropertyID
}

func (d *DeleteMetadataPropertyOptionRequest) GetOptionID() string {
	if d == nil {
		return ""
	}
	return d.OptionID
}

func (d *DeleteMetadataPropertyOptionRequest) GetType() components.PropertyType {
	if d == nil {
		return components.PropertyType("")
	}
	return d.Type
}

func (d *DeleteMetadataPropertyOptionRequest) GetListID() *string {
	if d == nil {
		return nil
	}
	return d.ListID
}

type DeleteMetadataPropertyOptionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Headers  map[string][]string
}

func (d *DeleteMetadataPropertyOptionResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteMetadataPropertyOptionResponse) GetHeaders() map[string][]string {
	if d == nil {
		return map[string][]string{}
	}
	return d.Headers
}
