// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
	"openapi/internal/sdk/sdkinternal/utils"
)

type DuplicateObjectRequest struct {
	TeamID     string                `pathParam:"style=simple,explode=false,name=teamId"`
	ObjectType components.ObjectType `pathParam:"style=simple,explode=false,name=objectType"`
	ObjectID   string                `pathParam:"style=simple,explode=false,name=objectId"`
	// A unique key (UUID or any opaque string up to 255 chars) that identifies this logical request. The server caches the first response under this key for 24 hours and replays it on retry — safe to use on every POST/PUT/PATCH to make network retries deterministic. Reusing the same key with a different body returns 409 `idempotency_key_mismatch`. Replays include the `idempotent-replay: true` response header.
	IdempotencyKey *string `header:"style=simple,explode=false,name=Idempotency-Key"`
}

func (d *DuplicateObjectRequest) GetTeamID() string {
	if d == nil {
		return ""
	}
	return d.TeamID
}

func (d *DuplicateObjectRequest) GetObjectType() components.ObjectType {
	if d == nil {
		return components.ObjectType("")
	}
	return d.ObjectType
}

func (d *DuplicateObjectRequest) GetObjectID() string {
	if d == nil {
		return ""
	}
	return d.ObjectID
}

func (d *DuplicateObjectRequest) GetIdempotencyKey() *string {
	if d == nil {
		return nil
	}
	return d.IdempotencyKey
}

type DuplicateObjectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Object duplicated. Returns the full new record (same shape as create).
	PrismObjectResponse *components.PrismObjectResponse
	Headers             map[string][]string
}

func (d DuplicateObjectResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DuplicateObjectResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DuplicateObjectResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DuplicateObjectResponse) GetPrismObjectResponse() *components.PrismObjectResponse {
	if d == nil {
		return nil
	}
	return d.PrismObjectResponse
}

func (d *DuplicateObjectResponse) GetHeaders() map[string][]string {
	if d == nil {
		return map[string][]string{}
	}
	return d.Headers
}
