// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
	"openapi/internal/sdk/sdkinternal/utils"
)

type FindObjectBySlugRequest struct {
	TeamID     string                `pathParam:"style=simple,explode=false,name=teamId"`
	ObjectType components.ObjectType `pathParam:"style=simple,explode=false,name=objectType"`
	// Property slug to match (e.g. `email`).
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
	// Property value to match exactly. URL-encode special characters.
	Value string `pathParam:"style=simple,explode=false,name=value"`
	// Scope the lookup to a specific list/app.
	ListID *string `queryParam:"style=form,explode=true,name=list_id"`
}

func (f *FindObjectBySlugRequest) GetTeamID() string {
	if f == nil {
		return ""
	}
	return f.TeamID
}

func (f *FindObjectBySlugRequest) GetObjectType() components.ObjectType {
	if f == nil {
		return components.ObjectType("")
	}
	return f.ObjectType
}

func (f *FindObjectBySlugRequest) GetSlug() string {
	if f == nil {
		return ""
	}
	return f.Slug
}

func (f *FindObjectBySlugRequest) GetValue() string {
	if f == nil {
		return ""
	}
	return f.Value
}

func (f *FindObjectBySlugRequest) GetListID() *string {
	if f == nil {
		return nil
	}
	return f.ListID
}

type FindObjectBySlugResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Matched record
	PrismObjectResponse *components.PrismObjectResponse
	Headers             map[string][]string
}

func (f FindObjectBySlugResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FindObjectBySlugResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FindObjectBySlugResponse) GetHTTPMeta() components.HTTPMetadata {
	if f == nil {
		return components.HTTPMetadata{}
	}
	return f.HTTPMeta
}

func (f *FindObjectBySlugResponse) GetPrismObjectResponse() *components.PrismObjectResponse {
	if f == nil {
		return nil
	}
	return f.PrismObjectResponse
}

func (f *FindObjectBySlugResponse) GetHeaders() map[string][]string {
	if f == nil {
		return map[string][]string{}
	}
	return f.Headers
}
