// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
)

type GetGrantRequest struct {
	TeamID     string                `pathParam:"style=simple,explode=false,name=teamId"`
	ObjectType components.ObjectType `pathParam:"style=simple,explode=false,name=objectType"`
	ObjectID   string                `pathParam:"style=simple,explode=false,name=objectId"`
}

func (g *GetGrantRequest) GetTeamID() string {
	if g == nil {
		return ""
	}
	return g.TeamID
}

func (g *GetGrantRequest) GetObjectType() components.ObjectType {
	if g == nil {
		return components.ObjectType("")
	}
	return g.ObjectType
}

func (g *GetGrantRequest) GetObjectID() string {
	if g == nil {
		return ""
	}
	return g.ObjectID
}

type GetGrantResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GrantRequest *components.GrantRequestUnion
	Headers      map[string][]string
}

func (g *GetGrantResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetGrantResponse) GetGrantRequest() *components.GrantRequestUnion {
	if g == nil {
		return nil
	}
	return g.GrantRequest
}

func (g *GetGrantResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
