// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
	"openapi/internal/sdk/sdkinternal/utils"
)

type GetImportJobRequest struct {
	TeamID string `pathParam:"style=simple,explode=false,name=teamId"`
	// The `job_id` returned from POST /import.
	JobID string `pathParam:"style=simple,explode=false,name=jobId"`
}

func (g *GetImportJobRequest) GetTeamID() string {
	if g == nil {
		return ""
	}
	return g.TeamID
}

func (g *GetImportJobRequest) GetJobID() string {
	if g == nil {
		return ""
	}
	return g.JobID
}

type GetImportJobResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Current job state
	ImportJob *components.ImportJob
	Headers   map[string][]string
}

func (g GetImportJobResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetImportJobResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetImportJobResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetImportJobResponse) GetImportJob() *components.ImportJob {
	if g == nil {
		return nil
	}
	return g.ImportJob
}

func (g *GetImportJobResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
