// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
	"openapi/internal/sdk/sdkinternal/utils"
)

type GetMetadataPropertiesByObjectTypeRequest struct {
	TeamID     string                `pathParam:"style=simple,explode=false,name=teamId"`
	ObjectType components.ObjectType `pathParam:"style=simple,explode=false,name=objectType"`
	// Scope properties to a specific list/app.
	ListID   *string `queryParam:"style=form,explode=true,name=list_id"`
	Autofill *bool   `queryParam:"style=form,explode=true,name=autofill"`
	Term     *string `queryParam:"style=form,explode=true,name=term"`
}

func (g *GetMetadataPropertiesByObjectTypeRequest) GetTeamID() string {
	if g == nil {
		return ""
	}
	return g.TeamID
}

func (g *GetMetadataPropertiesByObjectTypeRequest) GetObjectType() components.ObjectType {
	if g == nil {
		return components.ObjectType("")
	}
	return g.ObjectType
}

func (g *GetMetadataPropertiesByObjectTypeRequest) GetListID() *string {
	if g == nil {
		return nil
	}
	return g.ListID
}

func (g *GetMetadataPropertiesByObjectTypeRequest) GetAutofill() *bool {
	if g == nil {
		return nil
	}
	return g.Autofill
}

func (g *GetMetadataPropertiesByObjectTypeRequest) GetTerm() *string {
	if g == nil {
		return nil
	}
	return g.Term
}

type GetMetadataPropertiesByObjectTypeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	MetadataPropertiesResponse map[string]components.MetadataPropertiesResponse
	Headers                    map[string][]string
}

func (g GetMetadataPropertiesByObjectTypeResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMetadataPropertiesByObjectTypeResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMetadataPropertiesByObjectTypeResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetMetadataPropertiesByObjectTypeResponse) GetMetadataPropertiesResponse() map[string]components.MetadataPropertiesResponse {
	if g == nil {
		return nil
	}
	return g.MetadataPropertiesResponse
}

func (g *GetMetadataPropertiesByObjectTypeResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
