// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
	"openapi/internal/sdk/sdkinternal/utils"
)

type GetMetadataPropertiesRequest struct {
	TeamID string `pathParam:"style=simple,explode=false,name=teamId"`
	// Scope properties to a specific list/app.
	ListID   *string `queryParam:"style=form,explode=true,name=list_id"`
	Autofill *bool   `queryParam:"style=form,explode=true,name=autofill"`
	Term     *string `queryParam:"style=form,explode=true,name=term"`
}

func (g *GetMetadataPropertiesRequest) GetTeamID() string {
	if g == nil {
		return ""
	}
	return g.TeamID
}

func (g *GetMetadataPropertiesRequest) GetListID() *string {
	if g == nil {
		return nil
	}
	return g.ListID
}

func (g *GetMetadataPropertiesRequest) GetAutofill() *bool {
	if g == nil {
		return nil
	}
	return g.Autofill
}

func (g *GetMetadataPropertiesRequest) GetTerm() *string {
	if g == nil {
		return nil
	}
	return g.Term
}

type GetMetadataPropertiesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	MetadataPropertiesResponse map[string]components.MetadataPropertiesResponse
	Headers                    map[string][]string
}

func (g GetMetadataPropertiesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMetadataPropertiesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMetadataPropertiesResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetMetadataPropertiesResponse) GetMetadataPropertiesResponse() map[string]components.MetadataPropertiesResponse {
	if g == nil {
		return nil
	}
	return g.MetadataPropertiesResponse
}

func (g *GetMetadataPropertiesResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
