// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
	"openapi/internal/sdk/sdkinternal/utils"
)

type GetObjectRequest struct {
	TeamID     string                `pathParam:"style=simple,explode=false,name=teamId"`
	ObjectType components.ObjectType `pathParam:"style=simple,explode=false,name=objectType"`
	ObjectID   string                `pathParam:"style=simple,explode=false,name=objectId"`
	// Comma-separated property slugs to return. Use dot notation for relationships. `id` is always returned at the top level. Defaults to all properties.
	Select *string `queryParam:"style=form,explode=true,name=select"`
}

func (g *GetObjectRequest) GetTeamID() string {
	if g == nil {
		return ""
	}
	return g.TeamID
}

func (g *GetObjectRequest) GetObjectType() components.ObjectType {
	if g == nil {
		return components.ObjectType("")
	}
	return g.ObjectType
}

func (g *GetObjectRequest) GetObjectID() string {
	if g == nil {
		return ""
	}
	return g.ObjectID
}

func (g *GetObjectRequest) GetSelect() *string {
	if g == nil {
		return nil
	}
	return g.Select
}

type GetObjectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PrismObjectResponse *components.PrismObjectResponse
	Headers             map[string][]string
}

func (g GetObjectResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetObjectResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetObjectResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetObjectResponse) GetPrismObjectResponse() *components.PrismObjectResponse {
	if g == nil {
		return nil
	}
	return g.PrismObjectResponse
}

func (g *GetObjectResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
