// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"openapi/internal/sdk/models/components"
	"openapi/internal/sdk/sdkinternal/utils"
)

type GetViewRequest struct {
	TeamID         string                    `pathParam:"style=simple,explode=false,name=teamId"`
	ViewObjectType components.ViewObjectType `pathParam:"style=simple,explode=false,name=viewObjectType"`
	ViewID         string                    `pathParam:"style=simple,explode=false,name=viewId"`
	// Comma-separated list of optional sub-resources to inline. Currently the only recognized value is `records` — when present, the response is `{view, records}` rather than the bare view bundle.
	Include *string `queryParam:"style=form,explode=true,name=include"`
	// Forwarded to the records sub-resource when `include=records`.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// Forwarded to the records sub-resource when `include=records`.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Page *int64 `queryParam:"style=form,explode=true,name=page"`
	// Forwarded to the records sub-resource when `include=records`.
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
}

func (g *GetViewRequest) GetTeamID() string {
	if g == nil {
		return ""
	}
	return g.TeamID
}

func (g *GetViewRequest) GetViewObjectType() components.ViewObjectType {
	if g == nil {
		return components.ViewObjectType("")
	}
	return g.ViewObjectType
}

func (g *GetViewRequest) GetViewID() string {
	if g == nil {
		return ""
	}
	return g.ViewID
}

func (g *GetViewRequest) GetInclude() *string {
	if g == nil {
		return nil
	}
	return g.Include
}

func (g *GetViewRequest) GetCursor() *string {
	if g == nil {
		return nil
	}
	return g.Cursor
}

func (g *GetViewRequest) GetPage() *int64 {
	if g == nil {
		return nil
	}
	return g.Page
}

func (g *GetViewRequest) GetLimit() *int64 {
	if g == nil {
		return nil
	}
	return g.Limit
}

type GetViewResponseBodyType string

const (
	GetViewResponseBodyTypeViewBundle            GetViewResponseBodyType = "ViewBundle"
	GetViewResponseBodyTypeViewBundleWithRecords GetViewResponseBodyType = "ViewBundleWithRecords"
	GetViewResponseBodyTypeUnknown               GetViewResponseBodyType = "Unknown"
)

// GetViewResponseBody - OK. Returns the view bundle by default; returns `{view, records}` when `include=records` is passed.
type GetViewResponseBody struct {
	ViewBundle            *components.ViewBundle            `queryParam:"inline" union:"member"`
	ViewBundleWithRecords *components.ViewBundleWithRecords `queryParam:"inline" union:"member"`
	UnknownRaw            json.RawMessage                   `json:"-" union:"unknown"`

	Type GetViewResponseBodyType
}

func CreateGetViewResponseBodyViewBundle(viewBundle components.ViewBundle) GetViewResponseBody {
	typ := GetViewResponseBodyTypeViewBundle

	return GetViewResponseBody{
		ViewBundle: &viewBundle,
		Type:       typ,
	}
}

func CreateGetViewResponseBodyViewBundleWithRecords(viewBundleWithRecords components.ViewBundleWithRecords) GetViewResponseBody {
	typ := GetViewResponseBodyTypeViewBundleWithRecords

	return GetViewResponseBody{
		ViewBundleWithRecords: &viewBundleWithRecords,
		Type:                  typ,
	}
}

func CreateGetViewResponseBodyUnknown(raw json.RawMessage) GetViewResponseBody {
	return GetViewResponseBody{
		UnknownRaw: raw,
		Type:       GetViewResponseBodyTypeUnknown,
	}
}

func (u GetViewResponseBody) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u GetViewResponseBody) IsUnknown() bool {
	return u.Type == GetViewResponseBodyTypeUnknown
}

func (u *GetViewResponseBody) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var viewBundle components.ViewBundle = components.ViewBundle{}
	if err := utils.UnmarshalJSON(data, &viewBundle, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  GetViewResponseBodyTypeViewBundle,
			Value: &viewBundle,
		})
	}

	var viewBundleWithRecords components.ViewBundleWithRecords = components.ViewBundleWithRecords{}
	if err := utils.UnmarshalJSON(data, &viewBundleWithRecords, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  GetViewResponseBodyTypeViewBundleWithRecords,
			Value: &viewBundleWithRecords,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = GetViewResponseBodyTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = GetViewResponseBodyTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(GetViewResponseBodyType)
	switch best.Type {
	case GetViewResponseBodyTypeViewBundle:
		u.ViewBundle = best.Value.(*components.ViewBundle)
		return nil
	case GetViewResponseBodyTypeViewBundleWithRecords:
		u.ViewBundleWithRecords = best.Value.(*components.ViewBundleWithRecords)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = GetViewResponseBodyTypeUnknown
	return nil
}

func (u GetViewResponseBody) MarshalJSON() ([]byte, error) {
	if u.ViewBundle != nil {
		return utils.MarshalJSON(u.ViewBundle, "", true)
	}

	if u.ViewBundleWithRecords != nil {
		return utils.MarshalJSON(u.ViewBundleWithRecords, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type GetViewResponseBody: all fields are null")
}

type GetViewResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK. Returns the view bundle by default; returns `{view, records}` when `include=records` is passed.
	OneOf   *GetViewResponseBody
	Headers map[string][]string
}

func (g *GetViewResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetViewResponse) GetOneOf() *GetViewResponseBody {
	if g == nil {
		return nil
	}
	return g.OneOf
}

func (g *GetViewResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
