// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
	"openapi/internal/sdk/sdkinternal/utils"
)

type ImportObjectsRequest struct {
	TeamID     string                      `pathParam:"style=simple,explode=false,name=teamId"`
	ObjectType components.ImportObjectType `pathParam:"style=simple,explode=false,name=objectType"`
	// A unique key (UUID or any opaque string up to 255 chars) that identifies this logical request. The server caches the first response under this key for 24 hours and replays it on retry — safe to use on every POST/PUT/PATCH to make network retries deterministic. Reusing the same key with a different body returns 409 `idempotency_key_mismatch`. Replays include the `idempotent-replay: true` response header.
	IdempotencyKey *string                  `header:"style=simple,explode=false,name=Idempotency-Key"`
	Body           components.ImportRequest `request:"mediaType=application/json"`
}

func (i *ImportObjectsRequest) GetTeamID() string {
	if i == nil {
		return ""
	}
	return i.TeamID
}

func (i *ImportObjectsRequest) GetObjectType() components.ImportObjectType {
	if i == nil {
		return components.ImportObjectType("")
	}
	return i.ObjectType
}

func (i *ImportObjectsRequest) GetIdempotencyKey() *string {
	if i == nil {
		return nil
	}
	return i.IdempotencyKey
}

func (i *ImportObjectsRequest) GetBody() components.ImportRequest {
	if i == nil {
		return components.ImportRequest{}
	}
	return i.Body
}

type ImportObjectsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Import complete (sync path for small batches). `status` is `complete`, `job_id` is null, and per-row outcomes are inlined under `results`.
	ImportJob *components.ImportJob
	Headers   map[string][]string
}

func (i ImportObjectsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *ImportObjectsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *ImportObjectsResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *ImportObjectsResponse) GetImportJob() *components.ImportJob {
	if i == nil {
		return nil
	}
	return i.ImportJob
}

func (i *ImportObjectsResponse) GetHeaders() map[string][]string {
	if i == nil {
		return map[string][]string{}
	}
	return i.Headers
}
