// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
	"openapi/internal/sdk/optionalnullable"
	"openapi/internal/sdk/sdkinternal/utils"
)

type ListViewRecordsRequest struct {
	TeamID         string                    `pathParam:"style=simple,explode=false,name=teamId"`
	ViewObjectType components.ViewObjectType `pathParam:"style=simple,explode=false,name=viewObjectType"`
	ViewID         string                    `pathParam:"style=simple,explode=false,name=viewId"`
	// Opaque cursor from a previous response's `next_cursor`. Pass it back unchanged to fetch the next page. When set, `page` and `limit` are derived from the cursor.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// Page number (1-based). Prefer `cursor`.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Page  *int64 `queryParam:"style=form,explode=true,name=page"`
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
}

func (l *ListViewRecordsRequest) GetTeamID() string {
	if l == nil {
		return ""
	}
	return l.TeamID
}

func (l *ListViewRecordsRequest) GetViewObjectType() components.ViewObjectType {
	if l == nil {
		return components.ViewObjectType("")
	}
	return l.ViewObjectType
}

func (l *ListViewRecordsRequest) GetViewID() string {
	if l == nil {
		return ""
	}
	return l.ViewID
}

func (l *ListViewRecordsRequest) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

func (l *ListViewRecordsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListViewRecordsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

// ListViewRecordsResponseBody - OK
type ListViewRecordsResponseBody struct {
	Data []map[string]any `json:"data"`
	// True if more records exist beyond this page.
	HasMore bool `json:"has_more"`
	// Opaque cursor for the next page; null when `has_more` is false.
	NextCursor optionalnullable.OptionalNullable[string] `json:"next_cursor,omitzero"`
}

func (l *ListViewRecordsResponseBody) GetData() []map[string]any {
	if l == nil {
		return []map[string]any{}
	}
	return l.Data
}

func (l *ListViewRecordsResponseBody) GetHasMore() bool {
	if l == nil {
		return false
	}
	return l.HasMore
}

func (l *ListViewRecordsResponseBody) GetNextCursor() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.NextCursor
}

type ListViewRecordsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Object  *ListViewRecordsResponseBody
	Headers map[string][]string
}

func (l ListViewRecordsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListViewRecordsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListViewRecordsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListViewRecordsResponse) GetObject() *ListViewRecordsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}

func (l *ListViewRecordsResponse) GetHeaders() map[string][]string {
	if l == nil {
		return map[string][]string{}
	}
	return l.Headers
}
