// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
	"openapi/internal/sdk/optionalnullable"
	"openapi/internal/sdk/sdkinternal/utils"
)

type ListObjectsRequest struct {
	TeamID     string                `pathParam:"style=simple,explode=false,name=teamId"`
	ObjectType components.ObjectType `pathParam:"style=simple,explode=false,name=objectType"`
	// Opaque cursor from a previous response's `next_cursor`. Pass it back unchanged to fetch the next page.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// Maximum number of rows to return. Capped server-side at 50.
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// Comma-separated list of slugs. Prefix with `-` for descending. Example: `sort=-updated_at,name`.
	Sort *string `queryParam:"style=form,explode=true,name=sort"`
	// Comma-separated property slugs to return. Use dot notation for relationships. `id` is always returned at the top level. Defaults to all properties.
	Select *string `queryParam:"style=form,explode=true,name=select"`
	// Scope properties to a specific list/app.
	ListID *string `queryParam:"style=form,explode=true,name=list_id"`
	// Include soft-deleted records. Pass the literal string `true`.
	Deleted *bool `queryParam:"style=form,explode=true,name=deleted"`
	// When set to `true`, the response includes a `total` field with the unpaginated row count. Costs an extra pass; prefer `GET .../count` for the unfiltered total.
	IncludeTotal *bool `queryParam:"style=form,explode=true,name=include_total"`
}

func (l *ListObjectsRequest) GetTeamID() string {
	if l == nil {
		return ""
	}
	return l.TeamID
}

func (l *ListObjectsRequest) GetObjectType() components.ObjectType {
	if l == nil {
		return components.ObjectType("")
	}
	return l.ObjectType
}

func (l *ListObjectsRequest) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

func (l *ListObjectsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListObjectsRequest) GetSort() *string {
	if l == nil {
		return nil
	}
	return l.Sort
}

func (l *ListObjectsRequest) GetSelect() *string {
	if l == nil {
		return nil
	}
	return l.Select
}

func (l *ListObjectsRequest) GetListID() *string {
	if l == nil {
		return nil
	}
	return l.ListID
}

func (l *ListObjectsRequest) GetDeleted() *bool {
	if l == nil {
		return nil
	}
	return l.Deleted
}

func (l *ListObjectsRequest) GetIncludeTotal() *bool {
	if l == nil {
		return nil
	}
	return l.IncludeTotal
}

// ListObjectsResponseBody - A page of records.
type ListObjectsResponseBody struct {
	Data []components.PrismQueryRow `json:"data"`
	// Accurate end-of-data signal — false on the last page, never forces clients to overshoot.
	HasMore    bool                                      `json:"has_more"`
	NextCursor optionalnullable.OptionalNullable[string] `json:"next_cursor,omitzero"`
	// Populated only when `?include_total=true` was passed.
	Total optionalnullable.OptionalNullable[int64] `json:"total,omitzero"`
}

func (l *ListObjectsResponseBody) GetData() []components.PrismQueryRow {
	if l == nil {
		return []components.PrismQueryRow{}
	}
	return l.Data
}

func (l *ListObjectsResponseBody) GetHasMore() bool {
	if l == nil {
		return false
	}
	return l.HasMore
}

func (l *ListObjectsResponseBody) GetNextCursor() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.NextCursor
}

func (l *ListObjectsResponseBody) GetTotal() optionalnullable.OptionalNullable[int64] {
	if l == nil {
		return nil
	}
	return l.Total
}

type ListObjectsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A page of records.
	Object  *ListObjectsResponseBody
	Headers map[string][]string
}

func (l ListObjectsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListObjectsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListObjectsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListObjectsResponse) GetObject() *ListObjectsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}

func (l *ListObjectsResponse) GetHeaders() map[string][]string {
	if l == nil {
		return map[string][]string{}
	}
	return l.Headers
}
