// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
	"openapi/internal/sdk/sdkinternal/utils"
)

type PatchMetadataPropertyOptionRequest struct {
	TeamID     string                `pathParam:"style=simple,explode=false,name=teamId"`
	ObjectType components.ObjectType `pathParam:"style=simple,explode=false,name=objectType"`
	PropertyID string                `pathParam:"style=simple,explode=false,name=propertyId"`
	OptionID   string                `pathParam:"style=simple,explode=false,name=optionId"`
	// A unique key (UUID or any opaque string up to 255 chars) that identifies this logical request. The server caches the first response under this key for 24 hours and replays it on retry — safe to use on every POST/PUT/PATCH to make network retries deterministic. Reusing the same key with a different body returns 409 `idempotency_key_mismatch`. Replays include the `idempotent-replay: true` response header.
	IdempotencyKey *string                        `header:"style=simple,explode=false,name=Idempotency-Key"`
	Body           components.PropertyOptionPatch `request:"mediaType=application/json"`
}

func (p *PatchMetadataPropertyOptionRequest) GetTeamID() string {
	if p == nil {
		return ""
	}
	return p.TeamID
}

func (p *PatchMetadataPropertyOptionRequest) GetObjectType() components.ObjectType {
	if p == nil {
		return components.ObjectType("")
	}
	return p.ObjectType
}

func (p *PatchMetadataPropertyOptionRequest) GetPropertyID() string {
	if p == nil {
		return ""
	}
	return p.PropertyID
}

func (p *PatchMetadataPropertyOptionRequest) GetOptionID() string {
	if p == nil {
		return ""
	}
	return p.OptionID
}

func (p *PatchMetadataPropertyOptionRequest) GetIdempotencyKey() *string {
	if p == nil {
		return nil
	}
	return p.IdempotencyKey
}

func (p *PatchMetadataPropertyOptionRequest) GetBody() components.PropertyOptionPatch {
	if p == nil {
		return components.PropertyOptionPatch{}
	}
	return p.Body
}

type PatchMetadataPropertyOptionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Option updated
	PropertyOption *components.PropertyOption
	Headers        map[string][]string
}

func (p PatchMetadataPropertyOptionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PatchMetadataPropertyOptionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PatchMetadataPropertyOptionResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PatchMetadataPropertyOptionResponse) GetPropertyOption() *components.PropertyOption {
	if p == nil {
		return nil
	}
	return p.PropertyOption
}

func (p *PatchMetadataPropertyOptionResponse) GetHeaders() map[string][]string {
	if p == nil {
		return map[string][]string{}
	}
	return p.Headers
}
