// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
	"openapi/internal/sdk/sdkinternal/utils"
)

type PatchViewRequest struct {
	TeamID         string                    `pathParam:"style=simple,explode=false,name=teamId"`
	ViewObjectType components.ViewObjectType `pathParam:"style=simple,explode=false,name=viewObjectType"`
	ViewID         string                    `pathParam:"style=simple,explode=false,name=viewId"`
	// A unique key (UUID or any opaque string up to 255 chars) that identifies this logical request. The server caches the first response under this key for 24 hours and replays it on retry — safe to use on every POST/PUT/PATCH to make network retries deterministic. Reusing the same key with a different body returns 409 `idempotency_key_mismatch`. Replays include the `idempotent-replay: true` response header.
	IdempotencyKey *string                    `header:"style=simple,explode=false,name=Idempotency-Key"`
	Body           components.ViewBundlePatch `request:"mediaType=application/json"`
}

func (p *PatchViewRequest) GetTeamID() string {
	if p == nil {
		return ""
	}
	return p.TeamID
}

func (p *PatchViewRequest) GetViewObjectType() components.ViewObjectType {
	if p == nil {
		return components.ViewObjectType("")
	}
	return p.ViewObjectType
}

func (p *PatchViewRequest) GetViewID() string {
	if p == nil {
		return ""
	}
	return p.ViewID
}

func (p *PatchViewRequest) GetIdempotencyKey() *string {
	if p == nil {
		return nil
	}
	return p.IdempotencyKey
}

func (p *PatchViewRequest) GetBody() components.ViewBundlePatch {
	if p == nil {
		return components.ViewBundlePatch{}
	}
	return p.Body
}

type PatchViewResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ViewBundle *components.ViewBundle
	Headers    map[string][]string
}

func (p PatchViewResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PatchViewResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PatchViewResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PatchViewResponse) GetViewBundle() *components.ViewBundle {
	if p == nil {
		return nil
	}
	return p.ViewBundle
}

func (p *PatchViewResponse) GetHeaders() map[string][]string {
	if p == nil {
		return map[string][]string{}
	}
	return p.Headers
}
