// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
	"openapi/internal/sdk/sdkinternal/utils"
)

type PatchObjectRequest struct {
	TeamID     string                `pathParam:"style=simple,explode=false,name=teamId"`
	ObjectType components.ObjectType `pathParam:"style=simple,explode=false,name=objectType"`
	ObjectID   string                `pathParam:"style=simple,explode=false,name=objectId"`
	// A unique key (UUID or any opaque string up to 255 chars) that identifies this logical request. The server caches the first response under this key for 24 hours and replays it on retry — safe to use on every POST/PUT/PATCH to make network retries deterministic. Reusing the same key with a different body returns 409 `idempotency_key_mismatch`. Replays include the `idempotent-replay: true` response header.
	IdempotencyKey *string `header:"style=simple,explode=false,name=Idempotency-Key"`
	// Optimistic concurrency. Pass back the `etag` header from a previous GET of this record; the write only proceeds if the record hasn't changed since. Mismatch → 412 `precondition_failed`. Use `*` to require the record exists (any ETag accepted).
	IfMatch *string                               `header:"style=simple,explode=false,name=If-Match"`
	Body    components.PrismObjectPropertiesUnion `request:"mediaType=application/json"`
}

func (p *PatchObjectRequest) GetTeamID() string {
	if p == nil {
		return ""
	}
	return p.TeamID
}

func (p *PatchObjectRequest) GetObjectType() components.ObjectType {
	if p == nil {
		return components.ObjectType("")
	}
	return p.ObjectType
}

func (p *PatchObjectRequest) GetObjectID() string {
	if p == nil {
		return ""
	}
	return p.ObjectID
}

func (p *PatchObjectRequest) GetIdempotencyKey() *string {
	if p == nil {
		return nil
	}
	return p.IdempotencyKey
}

func (p *PatchObjectRequest) GetIfMatch() *string {
	if p == nil {
		return nil
	}
	return p.IfMatch
}

func (p *PatchObjectRequest) GetBody() components.PrismObjectPropertiesUnion {
	if p == nil {
		return components.PrismObjectPropertiesUnion{}
	}
	return p.Body
}

type PatchObjectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Object updated
	PrismObjectResponse *components.PrismObjectResponse
	Headers             map[string][]string
}

func (p PatchObjectResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PatchObjectResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PatchObjectResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PatchObjectResponse) GetPrismObjectResponse() *components.PrismObjectResponse {
	if p == nil {
		return nil
	}
	return p.PrismObjectResponse
}

func (p *PatchObjectResponse) GetHeaders() map[string][]string {
	if p == nil {
		return map[string][]string{}
	}
	return p.Headers
}
