// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
)

type PinViewRecordRequest struct {
	TeamID         string                    `pathParam:"style=simple,explode=false,name=teamId"`
	ViewObjectType components.ViewObjectType `pathParam:"style=simple,explode=false,name=viewObjectType"`
	ViewID         string                    `pathParam:"style=simple,explode=false,name=viewId"`
	ObjectID       string                    `pathParam:"style=simple,explode=false,name=objectId"`
	// A unique key (UUID or any opaque string up to 255 chars) that identifies this logical request. The server caches the first response under this key for 24 hours and replays it on retry — safe to use on every POST/PUT/PATCH to make network retries deterministic. Reusing the same key with a different body returns 409 `idempotency_key_mismatch`. Replays include the `idempotent-replay: true` response header.
	IdempotencyKey *string `header:"style=simple,explode=false,name=Idempotency-Key"`
}

func (p *PinViewRecordRequest) GetTeamID() string {
	if p == nil {
		return ""
	}
	return p.TeamID
}

func (p *PinViewRecordRequest) GetViewObjectType() components.ViewObjectType {
	if p == nil {
		return components.ViewObjectType("")
	}
	return p.ViewObjectType
}

func (p *PinViewRecordRequest) GetViewID() string {
	if p == nil {
		return ""
	}
	return p.ViewID
}

func (p *PinViewRecordRequest) GetObjectID() string {
	if p == nil {
		return ""
	}
	return p.ObjectID
}

func (p *PinViewRecordRequest) GetIdempotencyKey() *string {
	if p == nil {
		return nil
	}
	return p.IdempotencyKey
}

type PinViewRecordResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Headers  map[string][]string
}

func (p *PinViewRecordResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PinViewRecordResponse) GetHeaders() map[string][]string {
	if p == nil {
		return map[string][]string{}
	}
	return p.Headers
}
