// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"openapi/internal/sdk/models/components"
	"openapi/internal/sdk/optionalnullable"
	"openapi/internal/sdk/sdkinternal/utils"
)

type ObjectType string

const (
	ObjectTypeDeal          ObjectType = "deal"
	ObjectTypeIdentity      ObjectType = "identity"
	ObjectTypeAiChatThread  ObjectType = "ai_chat_thread"
	ObjectTypeAiChatMessage ObjectType = "ai_chat_message"
	ObjectTypeDocument      ObjectType = "document"
	ObjectTypeOrganization  ObjectType = "organization"
	ObjectTypeContact       ObjectType = "contact"
	ObjectTypeAction        ObjectType = "action"
	ObjectTypeEvent         ObjectType = "event"
)

func (e ObjectType) ToPointer() *ObjectType {
	return &e
}
func (e *ObjectType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "deal":
		fallthrough
	case "identity":
		fallthrough
	case "ai_chat_thread":
		fallthrough
	case "ai_chat_message":
		fallthrough
	case "document":
		fallthrough
	case "organization":
		fallthrough
	case "contact":
		fallthrough
	case "action":
		fallthrough
	case "event":
		*e = ObjectType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ObjectType: %v", v)
	}
}

type FilterType string

const (
	FilterTypeStr        FilterType = "str"
	FilterTypeBoolean    FilterType = "boolean"
	FilterTypeArrayOfStr FilterType = "arrayOfStr"
)

type Filter struct {
	Str        *string  `queryParam:"inline" union:"member"`
	Boolean    *bool    `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`

	Type FilterType
}

func CreateFilterStr(str string) Filter {
	typ := FilterTypeStr

	return Filter{
		Str:  &str,
		Type: typ,
	}
}

func CreateFilterBoolean(boolean bool) Filter {
	typ := FilterTypeBoolean

	return Filter{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateFilterArrayOfStr(arrayOfStr []string) Filter {
	typ := FilterTypeArrayOfStr

	return Filter{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *Filter) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FilterTypeStr,
			Value: &str,
		})
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FilterTypeBoolean,
			Value: &boolean,
		})
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FilterTypeArrayOfStr,
			Value: arrayOfStr,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Filter", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Filter", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(FilterType)
	switch best.Type {
	case FilterTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case FilterTypeBoolean:
		u.Boolean = best.Value.(*bool)
		return nil
	case FilterTypeArrayOfStr:
		u.ArrayOfStr = best.Value.([]string)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Filter", string(data))
}

func (u Filter) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type Filter: all fields are null")
}

type Sort string

const (
	SortAsc  Sort = "asc"
	SortDesc Sort = "desc"
)

func (e Sort) ToPointer() *Sort {
	return &e
}
func (e *Sort) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = Sort(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Sort: %v", v)
	}
}

// Combinator - Logical operator for combining filters
type Combinator string

const (
	CombinatorAnd Combinator = "AND"
	CombinatorOr  Combinator = "OR"
)

func (e Combinator) ToPointer() *Combinator {
	return &e
}
func (e *Combinator) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "AND":
		fallthrough
	case "OR":
		*e = Combinator(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Combinator: %v", v)
	}
}

type Query struct {
	// Property slugs to select. Use dot notation for relationships (e.g. attendee.contact.first_name). `id` is always returned at the top level of each row and does not need to be selected.
	Select []string `json:"select"`
	// Filters as [{ slug: { operator: value } }]. For select/multiselect properties, values may be option slugs or option UUIDs.
	Filter []map[string]map[string]Filter `json:"filter,omitzero"`
	// Sort order as [{ slug: direction }]. Array order determines sort priority
	Sort []map[string]Sort `json:"sort,omitzero"`
	// Logical operator for combining filters
	Combinator *Combinator `default:"AND" json:"combinator"`
	ListID     *string     `json:"list_id,omitzero"`
	// Opaque cursor from a previous response's `next_cursor`. Pass it back unchanged to fetch the next page. When set, `page` and `limit` are derived from the cursor and any explicit values are ignored.
	Cursor *string `json:"cursor,omitzero"`
	// Page number (1-based). Prefer `cursor`. Page-number pagination drifts under concurrent writes; use it only for one-shot exports.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Page *int64 `json:"page,omitzero"`
	// Maximum number of rows to return. Capped server-side at 50; requests above the cap are rejected.
	Limit *int64 `json:"limit,omitzero"`
}

func (q Query) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *Query) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *Query) GetSelect() []string {
	if q == nil {
		return []string{}
	}
	return q.Select
}

func (q *Query) GetFilter() []map[string]map[string]Filter {
	if q == nil {
		return nil
	}
	return q.Filter
}

func (q *Query) GetSort() []map[string]Sort {
	if q == nil {
		return nil
	}
	return q.Sort
}

func (q *Query) GetCombinator() *Combinator {
	if q == nil {
		return nil
	}
	return q.Combinator
}

func (q *Query) GetListID() *string {
	if q == nil {
		return nil
	}
	return q.ListID
}

func (q *Query) GetCursor() *string {
	if q == nil {
		return nil
	}
	return q.Cursor
}

func (q *Query) GetPage() *int64 {
	if q == nil {
		return nil
	}
	return q.Page
}

func (q *Query) GetLimit() *int64 {
	if q == nil {
		return nil
	}
	return q.Limit
}

type IDType string

const (
	IDTypeStr        IDType = "str"
	IDTypeArrayOfStr IDType = "arrayOfStr"
)

type ID struct {
	Str        *string  `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`

	Type IDType
}

func CreateIDStr(str string) ID {
	typ := IDTypeStr

	return ID{
		Str:  &str,
		Type: typ,
	}
}

func CreateIDArrayOfStr(arrayOfStr []string) ID {
	typ := IDTypeArrayOfStr

	return ID{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *ID) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  IDTypeStr,
			Value: &str,
		})
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  IDTypeArrayOfStr,
			Value: arrayOfStr,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ID", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ID", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(IDType)
	switch best.Type {
	case IDTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case IDTypeArrayOfStr:
		u.ArrayOfStr = best.Value.([]string)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ID", string(data))
}

func (u ID) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type ID: all fields are null")
}

type QueryRequestBody struct {
	Query Query `json:"query"`
	// Alternative location for the opaque cursor (sibling of `query`). Use whichever feels more natural; if both are present, `query.cursor` wins.
	Cursor *string `json:"cursor,omitzero"`
	// When true, the response includes a `total` field with the unpaginated row count. Costs an additional pass over the result set — for unfiltered totals prefer `GET /v2/prism/{teamId}/{objectType}/count` instead.
	IncludeTotal *bool    `default:"false" json:"include_total"`
	ID           *ID      `json:"id,omitzero"`
	Deleted      *bool    `json:"deleted,omitzero"`
	Sources      []string `json:"sources,omitzero"`
	Boxes        []string `json:"boxes,omitzero"`
}

func (q QueryRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryRequestBody) GetQuery() Query {
	if q == nil {
		return Query{}
	}
	return q.Query
}

func (q *QueryRequestBody) GetCursor() *string {
	if q == nil {
		return nil
	}
	return q.Cursor
}

func (q *QueryRequestBody) GetIncludeTotal() *bool {
	if q == nil {
		return nil
	}
	return q.IncludeTotal
}

func (q *QueryRequestBody) GetID() *ID {
	if q == nil {
		return nil
	}
	return q.ID
}

func (q *QueryRequestBody) GetDeleted() *bool {
	if q == nil {
		return nil
	}
	return q.Deleted
}

func (q *QueryRequestBody) GetSources() []string {
	if q == nil {
		return nil
	}
	return q.Sources
}

func (q *QueryRequestBody) GetBoxes() []string {
	if q == nil {
		return nil
	}
	return q.Boxes
}

type QueryRequest struct {
	TeamID     string           `pathParam:"style=simple,explode=false,name=teamId"`
	ObjectType ObjectType       `pathParam:"style=simple,explode=false,name=objectType"`
	Body       QueryRequestBody `request:"mediaType=application/json"`
}

func (q *QueryRequest) GetTeamID() string {
	if q == nil {
		return ""
	}
	return q.TeamID
}

func (q *QueryRequest) GetObjectType() ObjectType {
	if q == nil {
		return ObjectType("")
	}
	return q.ObjectType
}

func (q *QueryRequest) GetBody() QueryRequestBody {
	if q == nil {
		return QueryRequestBody{}
	}
	return q.Body
}

// QueryResponseBody - Successful query
type QueryResponseBody struct {
	Data []components.PrismQueryRow `json:"data"`
	// Accurate end-of-data signal. False when this page contains the last record; true only when at least one more record exists. (Implementation note: the server fetches one extra row internally to determine this — clients never need to overshoot to discover the end.)
	HasMore bool `json:"has_more"`
	// Opaque cursor pointing at the next page. Pass it back unchanged in the request body (`cursor`) of the next call. Null when `has_more` is false.
	NextCursor optionalnullable.OptionalNullable[string] `json:"next_cursor,omitzero"`
	// Only populated when the request set `include_total: true`. Total number of records matching the query, ignoring pagination. Opt-in because it costs an additional pass over the result set.
	Total optionalnullable.OptionalNullable[int64] `json:"total,omitzero"`
}

func (q *QueryResponseBody) GetData() []components.PrismQueryRow {
	if q == nil {
		return []components.PrismQueryRow{}
	}
	return q.Data
}

func (q *QueryResponseBody) GetHasMore() bool {
	if q == nil {
		return false
	}
	return q.HasMore
}

func (q *QueryResponseBody) GetNextCursor() optionalnullable.OptionalNullable[string] {
	if q == nil {
		return nil
	}
	return q.NextCursor
}

func (q *QueryResponseBody) GetTotal() optionalnullable.OptionalNullable[int64] {
	if q == nil {
		return nil
	}
	return q.Total
}

type QueryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful query
	Object  *QueryResponseBody
	Headers map[string][]string
}

func (q QueryResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryResponse) GetHTTPMeta() components.HTTPMetadata {
	if q == nil {
		return components.HTTPMetadata{}
	}
	return q.HTTPMeta
}

func (q *QueryResponse) GetObject() *QueryResponseBody {
	if q == nil {
		return nil
	}
	return q.Object
}

func (q *QueryResponse) GetHeaders() map[string][]string {
	if q == nil {
		return map[string][]string{}
	}
	return q.Headers
}
