// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
)

type ReorderViewRecordsRequest struct {
	TeamID         string                    `pathParam:"style=simple,explode=false,name=teamId"`
	ViewObjectType components.ViewObjectType `pathParam:"style=simple,explode=false,name=viewObjectType"`
	ViewID         string                    `pathParam:"style=simple,explode=false,name=viewId"`
	// A unique key (UUID or any opaque string up to 255 chars) that identifies this logical request. The server caches the first response under this key for 24 hours and replays it on retry — safe to use on every POST/PUT/PATCH to make network retries deterministic. Reusing the same key with a different body returns 409 `idempotency_key_mismatch`. Replays include the `idempotent-replay: true` response header.
	IdempotencyKey *string                      `header:"style=simple,explode=false,name=Idempotency-Key"`
	Body           components.RecordOrderUpdate `request:"mediaType=application/json"`
}

func (r *ReorderViewRecordsRequest) GetTeamID() string {
	if r == nil {
		return ""
	}
	return r.TeamID
}

func (r *ReorderViewRecordsRequest) GetViewObjectType() components.ViewObjectType {
	if r == nil {
		return components.ViewObjectType("")
	}
	return r.ViewObjectType
}

func (r *ReorderViewRecordsRequest) GetViewID() string {
	if r == nil {
		return ""
	}
	return r.ViewID
}

func (r *ReorderViewRecordsRequest) GetIdempotencyKey() *string {
	if r == nil {
		return nil
	}
	return r.IdempotencyKey
}

func (r *ReorderViewRecordsRequest) GetBody() components.RecordOrderUpdate {
	if r == nil {
		return components.RecordOrderUpdate{}
	}
	return r.Body
}

type ReorderViewRecordsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Headers  map[string][]string
}

func (r *ReorderViewRecordsResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ReorderViewRecordsResponse) GetHeaders() map[string][]string {
	if r == nil {
		return map[string][]string{}
	}
	return r.Headers
}
