// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
	"openapi/internal/sdk/sdkinternal/utils"
)

type RestoreObjectRequest struct {
	TeamID     string                `pathParam:"style=simple,explode=false,name=teamId"`
	ObjectType components.ObjectType `pathParam:"style=simple,explode=false,name=objectType"`
	ObjectID   string                `pathParam:"style=simple,explode=false,name=objectId"`
	// A unique key (UUID or any opaque string up to 255 chars) that identifies this logical request. The server caches the first response under this key for 24 hours and replays it on retry — safe to use on every POST/PUT/PATCH to make network retries deterministic. Reusing the same key with a different body returns 409 `idempotency_key_mismatch`. Replays include the `idempotent-replay: true` response header.
	IdempotencyKey *string `header:"style=simple,explode=false,name=Idempotency-Key"`
}

func (r *RestoreObjectRequest) GetTeamID() string {
	if r == nil {
		return ""
	}
	return r.TeamID
}

func (r *RestoreObjectRequest) GetObjectType() components.ObjectType {
	if r == nil {
		return components.ObjectType("")
	}
	return r.ObjectType
}

func (r *RestoreObjectRequest) GetObjectID() string {
	if r == nil {
		return ""
	}
	return r.ObjectID
}

func (r *RestoreObjectRequest) GetIdempotencyKey() *string {
	if r == nil {
		return nil
	}
	return r.IdempotencyKey
}

type RestoreObjectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Object restored
	PrismObjectResponse *components.PrismObjectResponse
	Headers             map[string][]string
}

func (r RestoreObjectResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RestoreObjectResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RestoreObjectResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RestoreObjectResponse) GetPrismObjectResponse() *components.PrismObjectResponse {
	if r == nil {
		return nil
	}
	return r.PrismObjectResponse
}

func (r *RestoreObjectResponse) GetHeaders() map[string][]string {
	if r == nil {
		return map[string][]string{}
	}
	return r.Headers
}
