// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
)

type UnpinViewRecordRequest struct {
	TeamID         string                    `pathParam:"style=simple,explode=false,name=teamId"`
	ViewObjectType components.ViewObjectType `pathParam:"style=simple,explode=false,name=viewObjectType"`
	ViewID         string                    `pathParam:"style=simple,explode=false,name=viewId"`
	ObjectID       string                    `pathParam:"style=simple,explode=false,name=objectId"`
}

func (u *UnpinViewRecordRequest) GetTeamID() string {
	if u == nil {
		return ""
	}
	return u.TeamID
}

func (u *UnpinViewRecordRequest) GetViewObjectType() components.ViewObjectType {
	if u == nil {
		return components.ViewObjectType("")
	}
	return u.ViewObjectType
}

func (u *UnpinViewRecordRequest) GetViewID() string {
	if u == nil {
		return ""
	}
	return u.ViewID
}

func (u *UnpinViewRecordRequest) GetObjectID() string {
	if u == nil {
		return ""
	}
	return u.ObjectID
}

type UnpinViewRecordResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Headers  map[string][]string
}

func (u *UnpinViewRecordResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UnpinViewRecordResponse) GetHeaders() map[string][]string {
	if u == nil {
		return map[string][]string{}
	}
	return u.Headers
}
