// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
)

type UpdateGrantRequest struct {
	TeamID     string                `pathParam:"style=simple,explode=false,name=teamId"`
	ObjectType components.ObjectType `pathParam:"style=simple,explode=false,name=objectType"`
	ObjectID   string                `pathParam:"style=simple,explode=false,name=objectId"`
	// A unique key (UUID or any opaque string up to 255 chars) that identifies this logical request. The server caches the first response under this key for 24 hours and replays it on retry — safe to use on every POST/PUT/PATCH to make network retries deterministic. Reusing the same key with a different body returns 409 `idempotency_key_mismatch`. Replays include the `idempotent-replay: true` response header.
	IdempotencyKey *string                      `header:"style=simple,explode=false,name=Idempotency-Key"`
	Body           components.GrantRequestUnion `request:"mediaType=application/json"`
}

func (u *UpdateGrantRequest) GetTeamID() string {
	if u == nil {
		return ""
	}
	return u.TeamID
}

func (u *UpdateGrantRequest) GetObjectType() components.ObjectType {
	if u == nil {
		return components.ObjectType("")
	}
	return u.ObjectType
}

func (u *UpdateGrantRequest) GetObjectID() string {
	if u == nil {
		return ""
	}
	return u.ObjectID
}

func (u *UpdateGrantRequest) GetIdempotencyKey() *string {
	if u == nil {
		return nil
	}
	return u.IdempotencyKey
}

func (u *UpdateGrantRequest) GetBody() components.GrantRequestUnion {
	if u == nil {
		return components.GrantRequestUnion{}
	}
	return u.Body
}

type UpdateGrantResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Grant updated
	GrantRequest *components.GrantRequestUnion
	Headers      map[string][]string
}

func (u *UpdateGrantResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateGrantResponse) GetGrantRequest() *components.GrantRequestUnion {
	if u == nil {
		return nil
	}
	return u.GrantRequest
}

func (u *UpdateGrantResponse) GetHeaders() map[string][]string {
	if u == nil {
		return map[string][]string{}
	}
	return u.Headers
}
