// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
	"openapi/internal/sdk/sdkinternal/utils"
)

type UpsertObjectRequest struct {
	TeamID     string                `pathParam:"style=simple,explode=false,name=teamId"`
	ObjectType components.ObjectType `pathParam:"style=simple,explode=false,name=objectType"`
	Slug       string                `pathParam:"style=simple,explode=false,name=slug"`
	Value      string                `pathParam:"style=simple,explode=false,name=value"`
	// A unique key (UUID or any opaque string up to 255 chars) that identifies this logical request. The server caches the first response under this key for 24 hours and replays it on retry — safe to use on every POST/PUT/PATCH to make network retries deterministic. Reusing the same key with a different body returns 409 `idempotency_key_mismatch`. Replays include the `idempotent-replay: true` response header.
	IdempotencyKey *string                               `header:"style=simple,explode=false,name=Idempotency-Key"`
	Body           components.PrismObjectPropertiesUnion `request:"mediaType=application/json"`
}

func (u *UpsertObjectRequest) GetTeamID() string {
	if u == nil {
		return ""
	}
	return u.TeamID
}

func (u *UpsertObjectRequest) GetObjectType() components.ObjectType {
	if u == nil {
		return components.ObjectType("")
	}
	return u.ObjectType
}

func (u *UpsertObjectRequest) GetSlug() string {
	if u == nil {
		return ""
	}
	return u.Slug
}

func (u *UpsertObjectRequest) GetValue() string {
	if u == nil {
		return ""
	}
	return u.Value
}

func (u *UpsertObjectRequest) GetIdempotencyKey() *string {
	if u == nil {
		return nil
	}
	return u.IdempotencyKey
}

func (u *UpsertObjectRequest) GetBody() components.PrismObjectPropertiesUnion {
	if u == nil {
		return components.PrismObjectPropertiesUnion{}
	}
	return u.Body
}

type UpsertObjectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Existing record patched.
	PrismObjectResponse *components.PrismObjectResponse
	Headers             map[string][]string
}

func (u UpsertObjectResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpsertObjectResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpsertObjectResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpsertObjectResponse) GetPrismObjectResponse() *components.PrismObjectResponse {
	if u == nil {
		return nil
	}
	return u.PrismObjectResponse
}

func (u *UpsertObjectResponse) GetHeaders() map[string][]string {
	if u == nil {
		return map[string][]string{}
	}
	return u.Headers
}
