// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"openapi/internal/sdk/models/components"
)

// Error - Standard error envelope. Every non-2xx response from the v2 API uses this shape.
type Error struct {
	Error_   components.Error2       `json:"error"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &Error{}

func (e *Error) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
