// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/spf13/cobra"
	"openapi/internal/client"
	"openapi/internal/flagutil"
	"openapi/internal/interactive"
	"openapi/internal/output"
	"openapi/internal/sdk/models/operations"
	"openapi/internal/usage"
)

var batchDeleteObjectsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "team-id", Shorthand: "t", FieldPath: "TeamID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "object-type", FieldPath: "ObjectType", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"comment", "deal", "engagement", "identity", "ai_chat_thread", "ai_chat_message", "document", "action", "event", "organization", "contact"}, Description: "options: comment, deal, engagement, identity, ai_chat_thread, ai_chat_message, document, action, event, organization, contact [required]"},
	{FlagName: "idempotency-key", FieldPath: "IdempotencyKey", Kind: flagutil.FlagKindString, Optional: true, Description: "A unique key (UUID or any opaque string up to 255 chars) that identifies this logical request. The server caches the first response under this key for 24 hours and replays it on retry — safe to use on every POST/PUT/PATCH to make network retries deterministic. Reusing the same key with a different body returns 409 `idempotency_key_mismatch`. Replays include the `idempotent-replay: true` response header."},
	{FlagName: "ids", FieldPath: "Body.Ids", Kind: flagutil.FlagKindStringArray, Required: true, Description: "[required]"},
}

// initBatchDeleteObjectsCmd initializes the batch-delete-objects command.
func initBatchDeleteObjectsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "batch-delete-objects",
		Short:   "Bulk delete records (partial success)",
		Long:    "Soft-delete up to 100 records in a single call. Same partial-success contract as batch/update.",
		Example: "  cli SDK batch-delete-objects --team-id 95aef178-55b0-4a28-a504-e7907ae2bb78 --object-type action --ids '[]'",
		RunE:    runBatchDeleteObjectsCmd,
		Aliases: []string{"bdo"},
	}
	flagutil.RegisterFlags(cmd, batchDeleteObjectsCmdMeta)
	if err := flagutil.ValidateMeta[operations.BatchDeleteObjectsRequest](batchDeleteObjectsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for batch-delete-objects: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runBatchDeleteObjectsCmd executes the batch-delete-objects command.
func runBatchDeleteObjectsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, batchDeleteObjectsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, batchDeleteObjectsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.BatchDeleteObjectsRequest](cmd, batchDeleteObjectsCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.BatchDeleteObjects(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
