// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/spf13/cobra"
	"openapi/internal/client"
	"openapi/internal/flagutil"
	"openapi/internal/interactive"
	"openapi/internal/output"
	"openapi/internal/sdk/models/operations"
	"openapi/internal/usage"
)

var batchUpdateObjectsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "team-id", Shorthand: "t", FieldPath: "TeamID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "object-type", FieldPath: "ObjectType", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"deal", "identity", "ai_chat_thread", "ai_chat_message", "document", "action", "event", "organization", "contact"}, Description: "options: deal, identity, ai_chat_thread, ai_chat_message, document, action, event, organization, contact [required]"},
	{FlagName: "idempotency-key", FieldPath: "IdempotencyKey", Kind: flagutil.FlagKindString, Optional: true, Description: "A unique key (UUID or any opaque string up to 255 chars) that identifies this logical request. The server caches the first response under this key for 24 hours and replays it on retry — safe to use on every POST/PUT/PATCH to make network retries deterministic. Reusing the same key with a different body returns 409 `idempotency_key_mismatch`. Replays include the `idempotent-replay: true` response header."},
	{FlagName: "items", FieldPath: "Body.Items", Kind: flagutil.FlagKindJSON, Required: true, Annotations: `json:"items"`, Description: "[required]"},
}

// initBatchUpdateObjectsCmd initializes the batch-update-objects command.
func initBatchUpdateObjectsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "batch-update-objects",
		Short:   "Bulk update records (partial success)",
		Long:    "Patch up to 100 records in a single call. Each item is attempted independently — failures don't abort the batch. Inspect `results[].status` per item.",
		Example: "  cli SDK batch-update-objects --team-id 8b4a4ef5-5244-4c0c-b879-78d0edf7068d --object-type ai_chat_message --items '[]'",
		RunE:    runBatchUpdateObjectsCmd,
		Aliases: []string{"buo"},
	}
	flagutil.RegisterFlags(cmd, batchUpdateObjectsCmdMeta)
	if err := flagutil.ValidateMeta[operations.BatchUpdateObjectsRequest](batchUpdateObjectsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for batch-update-objects: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runBatchUpdateObjectsCmd executes the batch-update-objects command.
func runBatchUpdateObjectsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, batchUpdateObjectsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, batchUpdateObjectsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.BatchUpdateObjectsRequest](cmd, batchUpdateObjectsCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.BatchUpdateObjects(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
