// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/spf13/cobra"
	"openapi/internal/client"
	"openapi/internal/flagutil"
	"openapi/internal/interactive"
	"openapi/internal/output"
	"openapi/internal/sdk/models/operations"
	"openapi/internal/usage"
)

var countObjectsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "team-id", Shorthand: "t", FieldPath: "TeamID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "object-type", FieldPath: "ObjectType", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"deal", "identity", "ai_chat_thread", "ai_chat_message", "document", "action", "event", "organization", "contact"}, Description: "options: deal, identity, ai_chat_thread, ai_chat_message, document, action, event, organization, contact [required]"},
	{FlagName: "list-id", Shorthand: "l", FieldPath: "ListID", Kind: flagutil.FlagKindString, Optional: true, Description: "Scope the count to a specific list/app."},
}

// initCountObjectsCmd initializes the count-objects command.
func initCountObjectsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "count-objects",
		Short:   "Total record count for an object type",
		Long:    "Returns the total number of records of this object type that the caller can see. Avoids the page-overshoot anti-pattern — clients no longer need to keep paging until `has_more` flips false to discover the total. Currently does not apply query filters; for a filtered total, pass `include_total: true` in a POST `/query` body.",
		Example: "  cli SDK count-objects --team-id 334bc1a2-d093-4be8-8078-f7ef2fa13681 --object-type organization",
		RunE:    runCountObjectsCmd,
		Aliases: []string{"co"},
	}
	flagutil.RegisterFlags(cmd, countObjectsCmdMeta)
	if err := flagutil.ValidateMeta[operations.CountObjectsRequest](countObjectsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for count-objects: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runCountObjectsCmd executes the count-objects command.
func runCountObjectsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, countObjectsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, countObjectsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.CountObjectsRequest](cmd, countObjectsCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.CountObjects(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
