// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/spf13/cobra"
	"openapi/internal/client"
	"openapi/internal/flagutil"
	"openapi/internal/interactive"
	"openapi/internal/output"
	"openapi/internal/sdk/models/operations"
	"openapi/internal/usage"
)

var createViewCmdMeta = []flagutil.FlagMeta{
	{FlagName: "team-id", Shorthand: "t", FieldPath: "TeamID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "view-object-type", Shorthand: "v", FieldPath: "ViewObjectType", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"comment", "action", "deal", "engagement", "document", "event", "identity", "organization"}, Description: "options: comment, action, deal, engagement, document, event, identity, organization [required]"},
	{FlagName: "idempotency-key", Shorthand: "i", FieldPath: "IdempotencyKey", Kind: flagutil.FlagKindString, Optional: true, Description: "A unique key (UUID or any opaque string up to 255 chars) that identifies this logical request. The server caches the first response under this key for 24 hours and replays it on retry — safe to use on every POST/PUT/PATCH to make network retries deterministic. Reusing the same key with a different body returns 409 `idempotency_key_mismatch`. Replays include the `idempotent-replay: true` response header."},
	{FlagName: "body-param.id", FieldPath: "Body.ID", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "body-param.team-id", FieldPath: "Body.TeamID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"team_id,omitempty"`, Description: "string value"},
	{FlagName: "body-param.list-id", FieldPath: "Body.ListID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"list_id,omitempty"`, Description: "string value"},
	{FlagName: "body-param.user-id", FieldPath: "Body.UserID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"user_id,omitempty"`, Description: "string value"},
	{FlagName: "body-param.name", FieldPath: "Body.Name", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "body-param.icon", FieldPath: "Body.Icon", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"icon,omitempty"`, Description: "string value"},
	{FlagName: "body-param.view-type", FieldPath: "Body.ViewType", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "body-param.combinator", FieldPath: "Body.Combinator", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"AND", "OR"}, Description: "options: AND, OR"},
	{FlagName: "body-param.sort-order", FieldPath: "Body.SortOrder", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"sort_order,omitempty"`, Description: "integer value"},
	{FlagName: "body-param.column-layout", FieldPath: "Body.ColumnLayout", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"column_layout,omitempty"`, Description: "value"},
	{FlagName: "body-param.group-by", FieldPath: "Body.GroupBy", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"group_by,omitempty"`, Description: "Property slug to group by"},
	{FlagName: "body-param.group-sort", FieldPath: "Body.GroupSort", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"group_sort,omitempty"`, Description: "string value"},
	{FlagName: "body-param.group-hide-empty", FieldPath: "Body.GroupHideEmpty", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"group_hide_empty,omitempty"`, Description: "boolean flag"},
	{FlagName: "body-param.group-hidden-option-ids", FieldPath: "Body.GroupHiddenOptionIds", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: array of any | ViewBundle_group_hidden_option_ids)"}},
	{FlagName: "body-param.aggregation-type", FieldPath: "Body.AggregationType", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"aggregation_type,omitempty"`, Description: "string value"},
	{FlagName: "body-param.aggregation-prop-def-id", FieldPath: "Body.AggregationPropDefID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"aggregation_prop_def_id,omitempty"`, Description: "string value"},
	{FlagName: "body-param.select", FieldPath: "Body.Select", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Property slugs (dot-paths permitted for refs)"},
	{FlagName: "body-param.filter", FieldPath: "Body.Filter", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"filter,omitempty"`, Description: "Each entry is { slug: { comparator: value } }"},
	{FlagName: "body-param.sort", FieldPath: "Body.Sort", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"sort,omitempty"`, Description: "Each entry is { slug: 'asc' | 'desc' }"},
	{FlagName: "body-param.created-at", FieldPath: "Body.CreatedAt", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "body-param.updated-at", FieldPath: "Body.UpdatedAt", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"updated_at,omitempty"`, Description: "string value"},
}

// initCreateViewCmd initializes the create-view command.
func initCreateViewCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create-view",
		Short:   "Create a view bundle (view + select/filter/sort)",
		Long:    "Create a view bundle (view + select/filter/sort)",
		Example: "  cli SDK create-view --team-id 408d4e54-e54c-4084-9e93-0fa16e13a37a --view-object-type organization --body-param.name <value> --body-param.view-type <value>",
		RunE:    runCreateViewCmd,
		Aliases: []string{"cv"},
	}
	flagutil.RegisterFlags(cmd, createViewCmdMeta)
	if err := flagutil.ValidateMeta[operations.CreateViewRequest](createViewCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create-view: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateViewCmd executes the create-view command.
func runCreateViewCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createViewCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createViewCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.CreateViewRequest](cmd, createViewCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.CreateView(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
