// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/spf13/cobra"
	"openapi/internal/client"
	"openapi/internal/flagutil"
	"openapi/internal/interactive"
	"openapi/internal/output"
	"openapi/internal/sdk/models/operations"
	"openapi/internal/usage"
)

var createMetadataPropertyCmdMeta = []flagutil.FlagMeta{
	{FlagName: "team-id", FieldPath: "TeamID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "object-type", FieldPath: "ObjectType", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"comment", "deal", "engagement", "identity", "ai_chat_thread", "ai_chat_message", "document", "action", "event", "organization", "contact"}, Description: "options: comment, deal, engagement, identity, ai_chat_thread, ai_chat_message, document, action, event, organization, contact [required]"},
	{FlagName: "idempotency-key", FieldPath: "IdempotencyKey", Kind: flagutil.FlagKindString, Optional: true, Description: "A unique key (UUID or any opaque string up to 255 chars) that identifies this logical request. The server caches the first response under this key for 24 hours and replays it on retry — safe to use on every POST/PUT/PATCH to make network retries deterministic. Reusing the same key with a different body returns 409 `idempotency_key_mismatch`. Replays include the `idempotent-replay: true` response header."},
	{FlagName: "type", FieldPath: "Body.Type", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"num", "str", "bool", "date", "text", "byte", "select_str", "multi_str", "multiselect_str", "jsonb", "ref_identity", "ref_user", "ref_organization", "ref_organization_user", "ref_contact", "ref_thread", "ref_message", "ref_event", "ref_account", "multiref_ai_chat_message", "multiref_action", "multiref_contact", "multiref_label", "multiref_thread", "multiref_messages", "multiref_document", "multiref_identity", "multiref_organization", "multiref_organization_user", "multiref_engagement", "multiref_attendee", "multiref_meeting_entry", "multiref_read_receipt", "multiref_account"}, Description: "Storage type for a property definition. (options: num, str, bool, date, text, byte, select_str, multi_str, multiselect_str, jsonb, ref_identity, ref_user, ref_organization, ref_organization_user, ref_contact, ref_thread, ref_message, ref_event, ref_account, multiref_ai_chat_message, multiref_action, multiref_contact, multiref_label, multiref_thread, multiref_messages, multiref_document, multiref_identity, multiref_organization, multiref_organization_user, multiref_engagement, multiref_attendee, multiref_meeting_entry, multiref_read_receipt, multiref_account) [required]"},
	{FlagName: "name", Shorthand: "n", FieldPath: "Body.Name", Kind: flagutil.FlagKindString, Required: true, Description: "Human-readable name. Must be unique within (team, list). [required]"},
	{FlagName: "slug", Shorthand: "s", FieldPath: "Body.Slug", Kind: flagutil.FlagKindString, Optional: true, Description: "URL-safe identifier. Defaults to a slugified `name`. Disambiguated with a numeric suffix on conflict."},
	{FlagName: "icon", FieldPath: "Body.Icon", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"icon,omitempty"`, Description: "string value"},
	{FlagName: "list-id", Shorthand: "l", FieldPath: "Body.ListID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"list_id,omitempty"`, Description: "string value"},
	{FlagName: "options", FieldPath: "Body.Options", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"options,omitempty"`, Description: "Only honored when `type` is `select_str` or `multiselect_str`."},
}

// initCreateMetadataPropertyCmd initializes the create-metadata-property command.
func initCreateMetadataPropertyCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create-metadata-property",
		Short:   "Create a property definition",
		Long:    "Define a new property on this object type, scoped to the calling team. For `select_str` and `multiselect_str` types you may pre-seed the choices via `options`. Pass `list_id` in the body to also scope the definition to a specific list/app.",
		Example: "  cli SDK create-metadata-property --team-id ca34e81e-c9b3-4108-aade-5d4752c38ae4 --object-type action --type ref_organization_user --name <value>",
		RunE:    runCreateMetadataPropertyCmd,
		Aliases: []string{"cmp"},
	}
	flagutil.RegisterFlags(cmd, createMetadataPropertyCmdMeta)
	if err := flagutil.ValidateMeta[operations.CreateMetadataPropertyRequest](createMetadataPropertyCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create-metadata-property: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateMetadataPropertyCmd executes the create-metadata-property command.
func runCreateMetadataPropertyCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createMetadataPropertyCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createMetadataPropertyCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.CreateMetadataPropertyRequest](cmd, createMetadataPropertyCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.CreateMetadataProperty(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
