// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/spf13/cobra"
	"openapi/internal/client"
	"openapi/internal/flagutil"
	"openapi/internal/interactive"
	"openapi/internal/output"
	"openapi/internal/sdk/models/operations"
	"openapi/internal/usage"
)

var createMetadataPropertyOptionCmdMeta = []flagutil.FlagMeta{
	{FlagName: "team-id", FieldPath: "TeamID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "object-type", FieldPath: "ObjectType", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"deal", "identity", "ai_chat_thread", "ai_chat_message", "document", "action", "event", "organization", "contact"}, Description: "options: deal, identity, ai_chat_thread, ai_chat_message, document, action, event, organization, contact [required]"},
	{FlagName: "property-id", Shorthand: "p", FieldPath: "PropertyID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "idempotency-key", FieldPath: "IdempotencyKey", Kind: flagutil.FlagKindString, Optional: true, Description: "A unique key (UUID or any opaque string up to 255 chars) that identifies this logical request. The server caches the first response under this key for 24 hours and replays it on retry — safe to use on every POST/PUT/PATCH to make network retries deterministic. Reusing the same key with a different body returns 409 `idempotency_key_mismatch`. Replays include the `idempotent-replay: true` response header."},
	{FlagName: "type", FieldPath: "Body.Type", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"num", "str", "bool", "date", "text", "byte", "select_str", "multi_str", "multiselect_str", "jsonb", "ref_identity", "ref_user", "ref_organization", "ref_organization_user", "ref_contact", "ref_thread", "ref_message", "ref_event", "ref_account", "multiref_ai_chat_message", "multiref_action", "multiref_contact", "multiref_label", "multiref_thread", "multiref_messages", "multiref_document", "multiref_identity", "multiref_organization", "multiref_organization_user", "multiref_engagement", "multiref_attendee", "multiref_meeting_entry", "multiref_read_receipt", "multiref_account"}, Description: "Storage type for a property definition. (options: num, str, bool, date, text, byte, select_str, multi_str, multiselect_str, jsonb, ref_identity, ref_user, ref_organization, ref_organization_user, ref_contact, ref_thread, ref_message, ref_event, ref_account, multiref_ai_chat_message, multiref_action, multiref_contact, multiref_label, multiref_thread, multiref_messages, multiref_document, multiref_identity, multiref_organization, multiref_organization_user, multiref_engagement, multiref_attendee, multiref_meeting_entry, multiref_read_receipt, multiref_account) [required]"},
	{FlagName: "list-id", Shorthand: "l", FieldPath: "Body.ListID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"list_id,omitempty"`, Description: "Scope the option to a specific list/app."},
	{FlagName: "value", Shorthand: "v", FieldPath: "Body.Value", Kind: flagutil.FlagKindString, Required: true, Description: "Display value for the option. [required]"},
	{FlagName: "slug", FieldPath: "Body.Slug", Kind: flagutil.FlagKindString, Optional: true, Description: "URL-safe identifier. Defaults to a slugified `value`."},
	{FlagName: "color-scheme", Shorthand: "c", FieldPath: "Body.ColorScheme", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"color_scheme,omitempty"`, Description: "string value"},
	{FlagName: "sort-index", FieldPath: "Body.SortIndex", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"sort_index,omitempty"`, Description: "integer value"},
	{FlagName: "icon", FieldPath: "Body.Icon", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"icon,omitempty"`, Description: "string value"},
	{FlagName: "description", FieldPath: "Body.Description", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"description,omitempty"`, Description: "string value"},
	{FlagName: "option-group", FieldPath: "Body.OptionGroup", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"option_group,omitempty"`, Description: "string value"},
}

// initCreateMetadataPropertyOptionCmd initializes the create-metadata-property-option command.
func initCreateMetadataPropertyOptionCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create-metadata-property-option",
		Short:   "Add an option to a select property",
		Long:    "Adds a single option to a `select_str` or `multiselect_str` property definition. Body must include `type` so the server knows which per-type option table to write.",
		Example: "  cli SDK create-metadata-property-option --team-id 638bb81b-7e3c-4105-a7b3-b35949652b97 --object-type action --property-id e075c94a-7a24-4c9a-901c-f554ecee71f4 --type multiref_read_receipt --value <value>",
		RunE:    runCreateMetadataPropertyOptionCmd,
		Aliases: []string{"cmpo"},
	}
	flagutil.RegisterFlags(cmd, createMetadataPropertyOptionCmdMeta)
	if err := flagutil.ValidateMeta[operations.CreateMetadataPropertyOptionRequest](createMetadataPropertyOptionCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create-metadata-property-option: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateMetadataPropertyOptionCmd executes the create-metadata-property-option command.
func runCreateMetadataPropertyOptionCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createMetadataPropertyOptionCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createMetadataPropertyOptionCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.CreateMetadataPropertyOptionRequest](cmd, createMetadataPropertyOptionCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.CreateMetadataPropertyOption(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
