// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/spf13/cobra"
	"openapi/internal/client"
	"openapi/internal/flagutil"
	"openapi/internal/interactive"
	"openapi/internal/output"
	"openapi/internal/sdk/models/operations"
	"openapi/internal/usage"
)

var deleteViewCmdMeta = []flagutil.FlagMeta{
	{FlagName: "team-id", Shorthand: "t", FieldPath: "TeamID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "view-object-type", FieldPath: "ViewObjectType", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"comment", "action", "deal", "engagement", "document", "event", "identity", "organization"}, Description: "options: comment, action, deal, engagement, document, event, identity, organization [required]"},
	{FlagName: "view-id", FieldPath: "ViewID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initDeleteViewCmd initializes the delete-view command.
func initDeleteViewCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "delete-view",
		Short:   "Delete a view bundle",
		Long:    "Delete a view bundle",
		Example: "  cli SDK delete-view --team-id fad35233-f5c6-4e04-802c-f84eb6caa2a6 --view-object-type event --view-id ec8b9808-d964-43ef-b1eb-29e2b6a3a8ec",
		RunE:    runDeleteViewCmd,
		Aliases: []string{"dv"},
	}
	flagutil.RegisterFlags(cmd, deleteViewCmdMeta)
	if err := flagutil.ValidateMeta[operations.DeleteViewRequest](deleteViewCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for delete-view: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runDeleteViewCmd executes the delete-view command.
func runDeleteViewCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, deleteViewCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, deleteViewCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.DeleteViewRequest](cmd, deleteViewCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.DeleteView(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
