// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/spf13/cobra"
	"openapi/internal/client"
	"openapi/internal/flagutil"
	"openapi/internal/interactive"
	"openapi/internal/output"
	"openapi/internal/sdk/models/operations"
	"openapi/internal/usage"
)

var deleteObjectCmdMeta = []flagutil.FlagMeta{
	{FlagName: "team-id", Shorthand: "t", FieldPath: "TeamID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "object-type", FieldPath: "ObjectType", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"comment", "deal", "engagement", "identity", "ai_chat_thread", "ai_chat_message", "document", "action", "event", "organization", "contact"}, Description: "options: comment, deal, engagement, identity, ai_chat_thread, ai_chat_message, document, action, event, organization, contact [required]"},
	{FlagName: "object-id", FieldPath: "ObjectID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "if-match", Shorthand: "i", FieldPath: "IfMatch", Kind: flagutil.FlagKindString, Optional: true, Description: "Optimistic concurrency. Pass back the `etag` header from a previous GET of this record; the write only proceeds if the record hasn't changed since. Mismatch → 412 `precondition_failed`. Use `*` to require the record exists (any ETag accepted)."},
}

// initDeleteObjectCmd initializes the delete-object command.
func initDeleteObjectCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "delete-object",
		Short:   "Delete object",
		Long:    "Delete object",
		Example: "  cli SDK delete-object --team-id bb39ef04-8bee-4878-ba38-a537fd6e67c5 --object-type identity --object-id 2096d92b-1e2d-475e-b442-7992f9161602",
		RunE:    runDeleteObjectCmd,
		Aliases: []string{"do"},
	}
	flagutil.RegisterFlags(cmd, deleteObjectCmdMeta)
	if err := flagutil.ValidateMeta[operations.DeleteObjectRequest](deleteObjectCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for delete-object: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runDeleteObjectCmd executes the delete-object command.
func runDeleteObjectCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, deleteObjectCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, deleteObjectCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.DeleteObjectRequest](cmd, deleteObjectCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.DeleteObject(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
