// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/spf13/cobra"
	"openapi/internal/client"
	"openapi/internal/flagutil"
	"openapi/internal/interactive"
	"openapi/internal/output"
	"openapi/internal/sdk/models/operations"
	"openapi/internal/usage"
)

var findObjectBySlugCmdMeta = []flagutil.FlagMeta{
	{FlagName: "team-id", Shorthand: "t", FieldPath: "TeamID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "object-type", FieldPath: "ObjectType", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"comment", "deal", "engagement", "identity", "ai_chat_thread", "ai_chat_message", "document", "action", "event", "organization", "contact"}, Description: "options: comment, deal, engagement, identity, ai_chat_thread, ai_chat_message, document, action, event, organization, contact [required]"},
	{FlagName: "slug", Shorthand: "s", FieldPath: "Slug", Kind: flagutil.FlagKindString, Required: true, Description: "Property slug to match (e.g. `email`). [required]"},
	{FlagName: "value", Shorthand: "v", FieldPath: "Value", Kind: flagutil.FlagKindString, Required: true, Description: "Property value to match exactly. URL-encode special characters. [required]"},
	{FlagName: "list-id", Shorthand: "l", FieldPath: "ListID", Kind: flagutil.FlagKindString, Optional: true, Description: "Scope the lookup to a specific list/app."},
}

// initFindObjectBySlugCmd initializes the find-object-by-slug command.
func initFindObjectBySlugCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "find-object-by-slug",
		Short:   "Find a record by property value",
		Long:    "Returns the single record whose property `{slug}` equals `{value}`. 404 if nothing matches; 409 if more than one record matches.",
		Example: "  cli SDK find-object-by-slug --team-id e54fbad4-3704-4d6b-9abb-c3d409815b9a --object-type event --slug <value> --value <value>",
		RunE:    runFindObjectBySlugCmd,
		Aliases: []string{"fobs"},
	}
	flagutil.RegisterFlags(cmd, findObjectBySlugCmdMeta)
	if err := flagutil.ValidateMeta[operations.FindObjectBySlugRequest](findObjectBySlugCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for find-object-by-slug: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runFindObjectBySlugCmd executes the find-object-by-slug command.
func runFindObjectBySlugCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, findObjectBySlugCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, findObjectBySlugCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.FindObjectBySlugRequest](cmd, findObjectBySlugCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.FindObjectBySlug(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
