// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/spf13/cobra"
	"openapi/internal/client"
	"openapi/internal/flagutil"
	"openapi/internal/interactive"
	"openapi/internal/output"
	"openapi/internal/sdk/models/operations"
	"openapi/internal/usage"
)

var getGrantCmdMeta = []flagutil.FlagMeta{
	{FlagName: "team-id", Shorthand: "t", FieldPath: "TeamID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "object-type", FieldPath: "ObjectType", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"deal", "identity", "ai_chat_thread", "ai_chat_message", "document", "action", "event", "organization", "contact"}, Description: "options: deal, identity, ai_chat_thread, ai_chat_message, document, action, event, organization, contact [required]"},
	{FlagName: "object-id", FieldPath: "ObjectID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initGetGrantCmd initializes the get-grant command.
func initGetGrantCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-grant",
		Short:   "Get grant",
		Long:    "Get grant",
		Example: "  cli SDK get-grant --team-id a7c8db69-f631-4797-928a-3af1b86e627e --object-type organization --object-id 888a0c54-4d0a-4136-a6ae-bfb2987d2ed5",
		RunE:    runGetGrantCmd,
		Aliases: []string{"gg"},
	}
	flagutil.RegisterFlags(cmd, getGrantCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetGrantRequest](getGrantCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-grant: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetGrantCmd executes the get-grant command.
func runGetGrantCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getGrantCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getGrantCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetGrantRequest](cmd, getGrantCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.GetGrant(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
