// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/spf13/cobra"
	"openapi/internal/client"
	"openapi/internal/flagutil"
	"openapi/internal/interactive"
	"openapi/internal/output"
	"openapi/internal/sdk/models/operations"
	"openapi/internal/usage"
)

var getImportJobCmdMeta = []flagutil.FlagMeta{
	{FlagName: "team-id", Shorthand: "t", FieldPath: "TeamID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "job-id", Shorthand: "j", FieldPath: "JobID", Kind: flagutil.FlagKindString, Required: true, Description: "The `job_id` returned from POST /import. [required]"},
}

// initGetImportJobCmd initializes the get-import-job command.
func initGetImportJobCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-import-job",
		Short:   "Get the status of an import job",
		Long:    "Poll the status of an async import. Sync imports complete in the original response and don't appear here. Async jobs are retained for 7 days. Returns 404 once the job has expired.",
		Example: "  cli SDK get-import-job --team-id 7951e46f-5947-4685-9da7-54824ebc0f4d --job-id <id>",
		RunE:    runGetImportJobCmd,
		Aliases: []string{"gij"},
	}
	flagutil.RegisterFlags(cmd, getImportJobCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetImportJobRequest](getImportJobCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-import-job: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetImportJobCmd executes the get-import-job command.
func runGetImportJobCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getImportJobCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getImportJobCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetImportJobRequest](cmd, getImportJobCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.GetImportJob(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
