// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/spf13/cobra"
	"openapi/internal/client"
	"openapi/internal/flagutil"
	"openapi/internal/interactive"
	"openapi/internal/output"
	"openapi/internal/sdk/models/operations"
	"openapi/internal/usage"
)

var getMetadataPropertiesCmdMeta = []flagutil.FlagMeta{
	{FlagName: "team-id", FieldPath: "TeamID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "list-id", Shorthand: "l", FieldPath: "ListID", Kind: flagutil.FlagKindString, Optional: true, Description: "Scope properties to a specific list/app."},
	{FlagName: "autofill", Shorthand: "a", FieldPath: "Autofill", Kind: flagutil.FlagKindBool, Optional: true, Description: "boolean flag"},
	{FlagName: "term", FieldPath: "Term", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
}

// initGetMetadataPropertiesCmd initializes the get-metadata-properties command.
func initGetMetadataPropertiesCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-metadata-properties",
		Short:   "Get metadata properties",
		Long:    "Get metadata properties",
		Example: "  cli SDK get-metadata-properties --team-id 6c9deea2-be0e-4c08-ab7c-0ad7a92abede",
		RunE:    runGetMetadataPropertiesCmd,
		Aliases: []string{"gmp"},
	}
	flagutil.RegisterFlags(cmd, getMetadataPropertiesCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetMetadataPropertiesRequest](getMetadataPropertiesCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-metadata-properties: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetMetadataPropertiesCmd executes the get-metadata-properties command.
func runGetMetadataPropertiesCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getMetadataPropertiesCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getMetadataPropertiesCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetMetadataPropertiesRequest](cmd, getMetadataPropertiesCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.GetMetadataProperties(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
