// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/spf13/cobra"
	"openapi/internal/client"
	"openapi/internal/flagutil"
	"openapi/internal/interactive"
	"openapi/internal/output"
	"openapi/internal/sdk/models/operations"
	"openapi/internal/usage"
)

var getMetadataPropertiesByObjectTypeCmdMeta = []flagutil.FlagMeta{
	{FlagName: "team-id", FieldPath: "TeamID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "object-type", FieldPath: "ObjectType", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"deal", "identity", "ai_chat_thread", "ai_chat_message", "document", "action", "event", "organization", "contact"}, Description: "options: deal, identity, ai_chat_thread, ai_chat_message, document, action, event, organization, contact [required]"},
	{FlagName: "list-id", Shorthand: "l", FieldPath: "ListID", Kind: flagutil.FlagKindString, Optional: true, Description: "Scope properties to a specific list/app."},
	{FlagName: "autofill", Shorthand: "a", FieldPath: "Autofill", Kind: flagutil.FlagKindBool, Optional: true, Description: "boolean flag"},
	{FlagName: "term", FieldPath: "Term", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
}

// initGetMetadataPropertiesByObjectTypeCmd initializes the get-metadata-properties-by-object-type command.
func initGetMetadataPropertiesByObjectTypeCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-metadata-properties-by-object-type",
		Short:   "Get metadata properties by object type",
		Long:    "Get metadata properties by object type",
		Example: "  cli SDK get-metadata-properties-by-object-type --team-id ac306c5b-0e6e-40ac-9717-2cd3d2b051c3 --object-type ai_chat_thread",
		RunE:    runGetMetadataPropertiesByObjectTypeCmd,
		Aliases: []string{"gmpbot"},
	}
	flagutil.RegisterFlags(cmd, getMetadataPropertiesByObjectTypeCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetMetadataPropertiesByObjectTypeRequest](getMetadataPropertiesByObjectTypeCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-metadata-properties-by-object-type: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetMetadataPropertiesByObjectTypeCmd executes the get-metadata-properties-by-object-type command.
func runGetMetadataPropertiesByObjectTypeCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getMetadataPropertiesByObjectTypeCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getMetadataPropertiesByObjectTypeCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetMetadataPropertiesByObjectTypeRequest](cmd, getMetadataPropertiesByObjectTypeCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.GetMetadataPropertiesByObjectType(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
