// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/spf13/cobra"
	"openapi/internal/client"
	"openapi/internal/flagutil"
	"openapi/internal/interactive"
	"openapi/internal/output"
	"openapi/internal/sdk/models/operations"
	"openapi/internal/usage"
)

var patchViewCmdMeta = []flagutil.FlagMeta{
	{FlagName: "team-id", Shorthand: "t", FieldPath: "TeamID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "view-object-type", FieldPath: "ViewObjectType", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"action", "deal", "document", "event", "identity", "organization"}, Description: "options: action, deal, document, event, identity, organization [required]"},
	{FlagName: "view-id", FieldPath: "ViewID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "idempotency-key", Shorthand: "i", FieldPath: "IdempotencyKey", Kind: flagutil.FlagKindString, Optional: true, Description: "A unique key (UUID or any opaque string up to 255 chars) that identifies this logical request. The server caches the first response under this key for 24 hours and replays it on retry — safe to use on every POST/PUT/PATCH to make network retries deterministic. Reusing the same key with a different body returns 409 `idempotency_key_mismatch`. Replays include the `idempotent-replay: true` response header."},
	{FlagName: "body-param.name", FieldPath: "Body.Name", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "body-param.icon", FieldPath: "Body.Icon", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"icon,omitempty"`, Description: "string value"},
	{FlagName: "body-param.view-type", FieldPath: "Body.ViewType", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "body-param.combinator", FieldPath: "Body.Combinator", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"AND", "OR"}, Description: "options: AND, OR"},
	{FlagName: "body-param.sort-order", FieldPath: "Body.SortOrder", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"sort_order,omitempty"`, Description: "integer value"},
	{FlagName: "body-param.column-layout", FieldPath: "Body.ColumnLayout", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"column_layout,omitempty"`, Description: "value"},
	{FlagName: "body-param.team-id", FieldPath: "Body.TeamID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"team_id,omitempty"`, Description: "string value"},
	{FlagName: "body-param.list-id", FieldPath: "Body.ListID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"list_id,omitempty"`, Description: "string value"},
	{FlagName: "body-param.user-id", FieldPath: "Body.UserID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"user_id,omitempty"`, Description: "string value"},
	{FlagName: "body-param.group-by", FieldPath: "Body.GroupBy", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"group_by,omitempty"`, Description: "string value"},
	{FlagName: "body-param.group-sort", FieldPath: "Body.GroupSort", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"group_sort,omitempty"`, Description: "string value"},
	{FlagName: "body-param.group-hide-empty", FieldPath: "Body.GroupHideEmpty", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"group_hide_empty,omitempty"`, Description: "boolean flag"},
	{FlagName: "body-param.group-hidden-option-ids", FieldPath: "Body.GroupHiddenOptionIds", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: array of any | ViewBundlePatch_group_hidden_option_ids)"}},
	{FlagName: "body-param.aggregation-type", FieldPath: "Body.AggregationType", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"aggregation_type,omitempty"`, Description: "string value"},
	{FlagName: "body-param.aggregation-prop-def-id", FieldPath: "Body.AggregationPropDefID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"aggregation_prop_def_id,omitempty"`, Description: "string value"},
	{FlagName: "body-param.select", FieldPath: "Body.Select", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "list of values"},
	{FlagName: "body-param.filter", FieldPath: "Body.Filter", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"filter,omitempty"`, Description: "list of values"},
	{FlagName: "body-param.sort", FieldPath: "Body.Sort", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"sort,omitempty"`, Description: "list of values"},
}

// initPatchViewCmd initializes the patch-view command.
func initPatchViewCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "patch-view",
		Short:   "Update a view bundle (select/filter/sort arrays are replaced wholesale when supplied)",
		Long:    "Update a view bundle (select/filter/sort arrays are replaced wholesale when supplied)",
		Example: "  cli SDK patch-view --team-id 71d03c6d-331f-4ab0-a736-ed919385894f --view-object-type organization --view-id da4fdf5f-2002-43d8-9307-719c29ea935e",
		RunE:    runPatchViewCmd,
		Aliases: []string{"pv"},
	}
	flagutil.RegisterFlags(cmd, patchViewCmdMeta)
	if err := flagutil.ValidateMeta[operations.PatchViewRequest](patchViewCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for patch-view: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runPatchViewCmd executes the patch-view command.
func runPatchViewCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, patchViewCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, patchViewCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PatchViewRequest](cmd, patchViewCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.PatchView(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
