// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/spf13/cobra"
	"openapi/internal/client"
	"openapi/internal/flagutil"
	"openapi/internal/interactive"
	"openapi/internal/output"
	"openapi/internal/sdk/models/operations"
	"openapi/internal/usage"
)

var reorderViewRecordsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "team-id", Shorthand: "t", FieldPath: "TeamID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "view-object-type", FieldPath: "ViewObjectType", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"comment", "action", "deal", "engagement", "document", "event", "identity", "organization"}, Description: "options: comment, action, deal, engagement, document, event, identity, organization [required]"},
	{FlagName: "view-id", FieldPath: "ViewID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "idempotency-key", Shorthand: "i", FieldPath: "IdempotencyKey", Kind: flagutil.FlagKindString, Optional: true, Description: "A unique key (UUID or any opaque string up to 255 chars) that identifies this logical request. The server caches the first response under this key for 24 hours and replays it on retry — safe to use on every POST/PUT/PATCH to make network retries deterministic. Reusing the same key with a different body returns 409 `idempotency_key_mismatch`. Replays include the `idempotent-replay: true` response header."},
	{FlagName: "object-ids", FieldPath: "Body.ObjectIds", Kind: flagutil.FlagKindStringArray, Required: true, Description: "[required]"},
}

// initReorderViewRecordsCmd initializes the reorder-view-records command.
func initReorderViewRecordsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "reorder-view-records",
		Short:   "Bulk reorder pinned records",
		Long:    "Bulk reorder pinned records",
		Example: "  cli SDK reorder-view-records --team-id e7e8f968-7f65-450c-a491-7ed845dafc5d --view-object-type organization --view-id 865817ce-fd37-4afa-b47c-40ddb9aea061 --object-ids '[\"f9213dfa-b87d-4ac9-8859-50116fd1e918\",\"6c34d94d-1ef3-4581-892a-249058c8931a\",\"9bb9dc7e-0c94-41b7-913d-284158b2e9d1\"]'",
		RunE:    runReorderViewRecordsCmd,
		Aliases: []string{"rvr"},
	}
	flagutil.RegisterFlags(cmd, reorderViewRecordsCmdMeta)
	if err := flagutil.ValidateMeta[operations.ReorderViewRecordsRequest](reorderViewRecordsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for reorder-view-records: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runReorderViewRecordsCmd executes the reorder-view-records command.
func runReorderViewRecordsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, reorderViewRecordsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, reorderViewRecordsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ReorderViewRecordsRequest](cmd, reorderViewRecordsCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.ReorderViewRecords(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
