// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/spf13/cobra"
	"openapi/internal/client"
	"openapi/internal/flagutil"
	"openapi/internal/interactive"
	"openapi/internal/output"
	"openapi/internal/sdk/models/operations"
	"openapi/internal/usage"
)

var unpinViewRecordCmdMeta = []flagutil.FlagMeta{
	{FlagName: "team-id", Shorthand: "t", FieldPath: "TeamID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "view-object-type", FieldPath: "ViewObjectType", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"action", "deal", "document", "event", "identity", "organization"}, Description: "options: action, deal, document, event, identity, organization [required]"},
	{FlagName: "view-id", FieldPath: "ViewID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "object-id", FieldPath: "ObjectID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initUnpinViewRecordCmd initializes the unpin-view-record command.
func initUnpinViewRecordCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "unpin-view-record",
		Short:   "Unpin a record from the view",
		Long:    "Unpin a record from the view",
		Example: "  cli SDK unpin-view-record --team-id 6503d82a-a518-4343-ac14-d6ec97fe5b2c --view-object-type document --view-id 15414dcd-d5c0-4917-ac31-2a81fc1c8285 --object-id 6653be40-78a4-4d1d-8358-7989174daeba",
		RunE:    runUnpinViewRecordCmd,
		Aliases: []string{"uvr"},
	}
	flagutil.RegisterFlags(cmd, unpinViewRecordCmdMeta)
	if err := flagutil.ValidateMeta[operations.UnpinViewRecordRequest](unpinViewRecordCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for unpin-view-record: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runUnpinViewRecordCmd executes the unpin-view-record command.
func runUnpinViewRecordCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, unpinViewRecordCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, unpinViewRecordCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.UnpinViewRecordRequest](cmd, unpinViewRecordCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.UnpinViewRecord(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
