// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/sdk/sdkinternal/utils"
)

type BatchResultStatus string

const (
	BatchResultStatusOk    BatchResultStatus = "ok"
	BatchResultStatusError BatchResultStatus = "error"
)

func (e BatchResultStatus) ToPointer() *BatchResultStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *BatchResultStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "ok", "error":
			return true
		}
	}
	return false
}

type BatchResultError struct {
	Code    *string `json:"code,omitzero"`
	Message *string `json:"message,omitzero"`
}

func (b *BatchResultError) GetCode() *string {
	if b == nil {
		return nil
	}
	return b.Code
}

func (b *BatchResultError) GetMessage() *string {
	if b == nil {
		return nil
	}
	return b.Message
}

type BatchResultResult struct {
	// Item ID, or null if the input was unparseable.
	ID     *string           `json:"id"`
	Status BatchResultStatus `json:"status"`
	// Object returned by reads (get/create/patch/restore). id is always present.
	Record *PrismObjectResponse `json:"record,omitzero"`
	Error  *BatchResultError    `json:"error,omitzero"`
}

func (b BatchResultResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BatchResultResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BatchResultResult) GetID() *string {
	if b == nil {
		return nil
	}
	return b.ID
}

func (b *BatchResultResult) GetStatus() BatchResultStatus {
	if b == nil {
		return BatchResultStatus("")
	}
	return b.Status
}

func (b *BatchResultResult) GetRecord() *PrismObjectResponse {
	if b == nil {
		return nil
	}
	return b.Record
}

func (b *BatchResultResult) GetError() *BatchResultError {
	if b == nil {
		return nil
	}
	return b.Error
}

type Summary struct {
	Total     int64 `json:"total"`
	Succeeded int64 `json:"succeeded"`
	Failed    int64 `json:"failed"`
}

func (s *Summary) GetTotal() int64 {
	if s == nil {
		return 0
	}
	return s.Total
}

func (s *Summary) GetSucceeded() int64 {
	if s == nil {
		return 0
	}
	return s.Succeeded
}

func (s *Summary) GetFailed() int64 {
	if s == nil {
		return 0
	}
	return s.Failed
}

// BatchResult - Partial-success bulk operation result. Inspect `results[].status` per item; the operation as a whole returns 200 even if some items failed.
type BatchResult struct {
	Results []BatchResultResult `json:"results"`
	Summary Summary             `json:"summary"`
}

func (b *BatchResult) GetResults() []BatchResultResult {
	if b == nil {
		return []BatchResultResult{}
	}
	return b.Results
}

func (b *BatchResult) GetSummary() Summary {
	if b == nil {
		return Summary{}
	}
	return b.Summary
}
