// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/sdk/sdkinternal/utils"
)

type Error1 struct {
	// JSON path of the offending property (e.g. ".body.default.email").
	Field   *string `json:"field,omitzero"`
	Message string  `json:"message"`
	// Validator-specific code (e.g. "required.openapi.validation").
	Code *string `json:"code,omitzero"`
}

func (e *Error1) GetField() *string {
	if e == nil {
		return nil
	}
	return e.Field
}

func (e *Error1) GetMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}

func (e *Error1) GetCode() *string {
	if e == nil {
		return nil
	}
	return e.Code
}

// #region class-body-error1
// #endregion class-body-error1

// Details - Optional bag of error-specific context. Shape varies by code; clients should treat fields as opaque unless documented.
type Details struct {
}

type Error2 struct {
	// Stable machine-readable code. Branch on this, not on the HTTP status, to handle specific failure modes.
	Code string `json:"code"`
	// Human-readable summary suitable for logs. Not localized; do not display verbatim to end users.
	Message string `json:"message"`
	// Echo of the x-request-id response header. Include in support requests.
	RequestID *string `json:"request_id"`
	// For validation errors (code=invalid_request), the structured list of field-level issues.
	Errors []Error1 `json:"errors,omitzero"`
	// Optional bag of error-specific context. Shape varies by code; clients should treat fields as opaque unless documented.
	Details *Details `json:"details,omitzero"`
}

func (e Error2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *Error2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *Error2) GetCode() string {
	if e == nil {
		return ""
	}
	return e.Code
}

func (e *Error2) GetMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}

func (e *Error2) GetRequestID() *string {
	if e == nil {
		return nil
	}
	return e.RequestID
}

func (e *Error2) GetErrors() []Error1 {
	if e == nil {
		return nil
	}
	return e.Errors
}

func (e *Error2) GetDetails() *Details {
	if e == nil {
		return nil
	}
	return e.Details
}

// #region class-body-error2
// #endregion class-body-error2
