// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"openapi/internal/sdk/sdkinternal/utils"
)

type GrantRequest3 struct {
	UserID      []map[string]LevelEnum `json:"user_id,omitzero"`
	TeamID      map[string]LevelEnum   `json:"team_id,omitzero"`
	TeamGroupID []map[string]LevelEnum `json:"team_group_id"`
}

func (g GrantRequest3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GrantRequest3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GrantRequest3) GetUserID() []map[string]LevelEnum {
	if g == nil {
		return nil
	}
	return g.UserID
}

func (g *GrantRequest3) GetTeamID() map[string]LevelEnum {
	if g == nil {
		return nil
	}
	return g.TeamID
}

func (g *GrantRequest3) GetTeamGroupID() []map[string]LevelEnum {
	if g == nil {
		return []map[string]LevelEnum{}
	}
	return g.TeamGroupID
}

// #region class-body-grantrequest3
// #endregion class-body-grantrequest3

type GrantRequest2 struct {
	UserID      []map[string]LevelEnum `json:"user_id,omitzero"`
	TeamID      map[string]LevelEnum   `json:"team_id"`
	TeamGroupID []map[string]LevelEnum `json:"team_group_id,omitzero"`
}

func (g GrantRequest2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GrantRequest2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GrantRequest2) GetUserID() []map[string]LevelEnum {
	if g == nil {
		return nil
	}
	return g.UserID
}

func (g *GrantRequest2) GetTeamID() map[string]LevelEnum {
	if g == nil {
		return map[string]LevelEnum{}
	}
	return g.TeamID
}

func (g *GrantRequest2) GetTeamGroupID() []map[string]LevelEnum {
	if g == nil {
		return nil
	}
	return g.TeamGroupID
}

// #region class-body-grantrequest2
// #endregion class-body-grantrequest2

type GrantRequest1 struct {
	UserID      []map[string]LevelEnum `json:"user_id"`
	TeamID      map[string]LevelEnum   `json:"team_id,omitzero"`
	TeamGroupID []map[string]LevelEnum `json:"team_group_id,omitzero"`
}

func (g GrantRequest1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GrantRequest1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GrantRequest1) GetUserID() []map[string]LevelEnum {
	if g == nil {
		return []map[string]LevelEnum{}
	}
	return g.UserID
}

func (g *GrantRequest1) GetTeamID() map[string]LevelEnum {
	if g == nil {
		return nil
	}
	return g.TeamID
}

func (g *GrantRequest1) GetTeamGroupID() []map[string]LevelEnum {
	if g == nil {
		return nil
	}
	return g.TeamGroupID
}

// #region class-body-grantrequest1
// #endregion class-body-grantrequest1

type GrantRequestUnionType string

const (
	GrantRequestUnionTypeGrantRequest1 GrantRequestUnionType = "GrantRequest_1"
	GrantRequestUnionTypeGrantRequest2 GrantRequestUnionType = "GrantRequest_2"
	GrantRequestUnionTypeGrantRequest3 GrantRequestUnionType = "GrantRequest_3"
	GrantRequestUnionTypeUnknown       GrantRequestUnionType = "Unknown"
)

type GrantRequestUnion struct {
	GrantRequest1 *GrantRequest1  `queryParam:"inline" union:"member"`
	GrantRequest2 *GrantRequest2  `queryParam:"inline" union:"member"`
	GrantRequest3 *GrantRequest3  `queryParam:"inline" union:"member"`
	UnknownRaw    json.RawMessage `json:"-" union:"unknown"`

	Type GrantRequestUnionType
}

func CreateGrantRequestUnionGrantRequest1(grantRequest1 GrantRequest1) GrantRequestUnion {
	typ := GrantRequestUnionTypeGrantRequest1

	return GrantRequestUnion{
		GrantRequest1: &grantRequest1,
		Type:          typ,
	}
}

func CreateGrantRequestUnionGrantRequest2(grantRequest2 GrantRequest2) GrantRequestUnion {
	typ := GrantRequestUnionTypeGrantRequest2

	return GrantRequestUnion{
		GrantRequest2: &grantRequest2,
		Type:          typ,
	}
}

func CreateGrantRequestUnionGrantRequest3(grantRequest3 GrantRequest3) GrantRequestUnion {
	typ := GrantRequestUnionTypeGrantRequest3

	return GrantRequestUnion{
		GrantRequest3: &grantRequest3,
		Type:          typ,
	}
}

func CreateGrantRequestUnionUnknown(raw json.RawMessage) GrantRequestUnion {
	return GrantRequestUnion{
		UnknownRaw: raw,
		Type:       GrantRequestUnionTypeUnknown,
	}
}

func (u GrantRequestUnion) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u GrantRequestUnion) IsUnknown() bool {
	return u.Type == GrantRequestUnionTypeUnknown
}

func (u *GrantRequestUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var grantRequest1 GrantRequest1 = GrantRequest1{}
	if err := utils.UnmarshalJSON(data, &grantRequest1, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  GrantRequestUnionTypeGrantRequest1,
			Value: &grantRequest1,
		})
	}

	var grantRequest2 GrantRequest2 = GrantRequest2{}
	if err := utils.UnmarshalJSON(data, &grantRequest2, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  GrantRequestUnionTypeGrantRequest2,
			Value: &grantRequest2,
		})
	}

	var grantRequest3 GrantRequest3 = GrantRequest3{}
	if err := utils.UnmarshalJSON(data, &grantRequest3, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  GrantRequestUnionTypeGrantRequest3,
			Value: &grantRequest3,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = GrantRequestUnionTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = GrantRequestUnionTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(GrantRequestUnionType)
	switch best.Type {
	case GrantRequestUnionTypeGrantRequest1:
		u.GrantRequest1 = best.Value.(*GrantRequest1)
		return nil
	case GrantRequestUnionTypeGrantRequest2:
		u.GrantRequest2 = best.Value.(*GrantRequest2)
		return nil
	case GrantRequestUnionTypeGrantRequest3:
		u.GrantRequest3 = best.Value.(*GrantRequest3)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = GrantRequestUnionTypeUnknown
	return nil
}

func (u GrantRequestUnion) MarshalJSON() ([]byte, error) {
	if u.GrantRequest1 != nil {
		return utils.MarshalJSON(u.GrantRequest1, "", true)
	}

	if u.GrantRequest2 != nil {
		return utils.MarshalJSON(u.GrantRequest2, "", true)
	}

	if u.GrantRequest3 != nil {
		return utils.MarshalJSON(u.GrantRequest3, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type GrantRequestUnion: all fields are null")
}
