// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ImportObjectType string

const (
	ImportObjectTypeIdentity     ImportObjectType = "identity"
	ImportObjectTypeOrganization ImportObjectType = "organization"
	ImportObjectTypeContact      ImportObjectType = "contact"
	ImportObjectTypeAction       ImportObjectType = "action"
	ImportObjectTypeDocument     ImportObjectType = "document"
	ImportObjectTypeDeal         ImportObjectType = "deal"
)

func (e ImportObjectType) ToPointer() *ImportObjectType {
	return &e
}
func (e *ImportObjectType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "identity":
		fallthrough
	case "organization":
		fallthrough
	case "contact":
		fallthrough
	case "action":
		fallthrough
	case "document":
		fallthrough
	case "deal":
		*e = ImportObjectType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ImportObjectType: %v", v)
	}
}
