// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/sdk/sdkinternal/utils"
)

type OptionsObj struct {
	// Property slug to deduplicate on
	DedupeBy *string `json:"dedupe_by,omitzero"`
	// Whether deduplication should be case insensitive
	CaseInsensitive *bool `default:"true" json:"caseInsensitive"`
	// App/CRM ID for context (optional)
	ListID *string `json:"list_id,omitzero"`
}

func (o OptionsObj) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OptionsObj) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OptionsObj) GetDedupeBy() *string {
	if o == nil {
		return nil
	}
	return o.DedupeBy
}

func (o *OptionsObj) GetCaseInsensitive() *bool {
	if o == nil {
		return nil
	}
	return o.CaseInsensitive
}

func (o *OptionsObj) GetListID() *string {
	if o == nil {
		return nil
	}
	return o.ListID
}

type ImportRequest struct {
	// Array of objects to import with property values keyed by slug
	Objects []PrismObjectPropertiesUnion `json:"objects"`
	Options *OptionsObj                  `json:"options,omitzero"`
}

func (i ImportRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *ImportRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *ImportRequest) GetObjects() []PrismObjectPropertiesUnion {
	if i == nil {
		return []PrismObjectPropertiesUnion{}
	}
	return i.Objects
}

func (i *ImportRequest) GetOptions() *OptionsObj {
	if i == nil {
		return nil
	}
	return i.Options
}
