// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/sdk/optionalnullable"
	"openapi/internal/sdk/sdkinternal/utils"
	"time"
)

type ImportJobStatus string

const (
	ImportJobStatusComplete   ImportJobStatus = "complete"
	ImportJobStatusProcessing ImportJobStatus = "processing"
	ImportJobStatusFailed     ImportJobStatus = "failed"
)

func (e ImportJobStatus) ToPointer() *ImportJobStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ImportJobStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "complete", "processing", "failed":
			return true
		}
	}
	return false
}

type ImportJobResultError struct {
	Code    *string `json:"code,omitzero"`
	Message *string `json:"message,omitzero"`
}

func (i *ImportJobResultError) GetCode() *string {
	if i == nil {
		return nil
	}
	return i.Code
}

func (i *ImportJobResultError) GetMessage() *string {
	if i == nil {
		return nil
	}
	return i.Message
}

type ImportJobResult struct {
	ID      optionalnullable.OptionalNullable[string] `json:"id,omitzero"`
	Created *bool                                     `json:"created,omitzero"`
	// True if the row matched an existing record via the dedupe key.
	Existing *bool                 `json:"existing,omitzero"`
	Error    *ImportJobResultError `json:"error,omitzero"`
}

func (i ImportJobResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *ImportJobResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *ImportJobResult) GetID() optionalnullable.OptionalNullable[string] {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *ImportJobResult) GetCreated() *bool {
	if i == nil {
		return nil
	}
	return i.Created
}

func (i *ImportJobResult) GetExisting() *bool {
	if i == nil {
		return nil
	}
	return i.Existing
}

func (i *ImportJobResult) GetError() *ImportJobResultError {
	if i == nil {
		return nil
	}
	return i.Error
}

// ImportJobError - Set when status=failed; describes the job-level failure (not per-row).
type ImportJobError struct {
	Code    *string `json:"code,omitzero"`
	Message *string `json:"message,omitzero"`
}

func (i *ImportJobError) GetCode() *string {
	if i == nil {
		return nil
	}
	return i.Code
}

func (i *ImportJobError) GetMessage() *string {
	if i == nil {
		return nil
	}
	return i.Message
}

// ImportJob - Status snapshot of an import job. Same shape used by the POST /import response and by GET /imports/{jobId}.
type ImportJob struct {
	// Null for sync imports (results inlined). Set for async imports.
	JobID  *string         `json:"job_id"`
	Status ImportJobStatus `json:"status"`
	// Total number of rows in the import.
	Total int64 `json:"total"`
	// Rows that have been attempted (succeeded + failed).
	Processed *int64 `json:"processed,omitzero"`
	Succeeded *int64 `json:"succeeded,omitzero"`
	Failed    *int64 `json:"failed,omitzero"`
	// Per-row outcomes. Always present for sync imports; populated for async imports once the job reaches `complete`.
	Results []ImportJobResult `json:"results,omitzero"`
	// Set when status=failed; describes the job-level failure (not per-row).
	Error     *ImportJobError `json:"error,omitzero"`
	CreatedAt *time.Time      `json:"created_at,omitzero"`
	UpdatedAt *time.Time      `json:"updated_at,omitzero"`
	ExpiresAt *time.Time      `json:"expires_at,omitzero"`
}

func (i ImportJob) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *ImportJob) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *ImportJob) GetJobID() *string {
	if i == nil {
		return nil
	}
	return i.JobID
}

func (i *ImportJob) GetStatus() ImportJobStatus {
	if i == nil {
		return ImportJobStatus("")
	}
	return i.Status
}

func (i *ImportJob) GetTotal() int64 {
	if i == nil {
		return 0
	}
	return i.Total
}

func (i *ImportJob) GetProcessed() *int64 {
	if i == nil {
		return nil
	}
	return i.Processed
}

func (i *ImportJob) GetSucceeded() *int64 {
	if i == nil {
		return nil
	}
	return i.Succeeded
}

func (i *ImportJob) GetFailed() *int64 {
	if i == nil {
		return nil
	}
	return i.Failed
}

func (i *ImportJob) GetResults() []ImportJobResult {
	if i == nil {
		return nil
	}
	return i.Results
}

func (i *ImportJob) GetError() *ImportJobError {
	if i == nil {
		return nil
	}
	return i.Error
}

func (i *ImportJob) GetCreatedAt() *time.Time {
	if i == nil {
		return nil
	}
	return i.CreatedAt
}

func (i *ImportJob) GetUpdatedAt() *time.Time {
	if i == nil {
		return nil
	}
	return i.UpdatedAt
}

func (i *ImportJob) GetExpiresAt() *time.Time {
	if i == nil {
		return nil
	}
	return i.ExpiresAt
}
