// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LevelEnum string

const (
	LevelEnumA LevelEnum = "a"
	LevelEnumR LevelEnum = "r"
	LevelEnumW LevelEnum = "w"
)

func (e LevelEnum) ToPointer() *LevelEnum {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *LevelEnum) IsExact() bool {
	if e != nil {
		switch *e {
		case "a", "r", "w":
			return true
		}
	}
	return false
}
