// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// MetadataPropertiesResponse - Property definitions for one object type, keyed by property definition id (UUID).
type MetadataPropertiesResponse struct {
}
