// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ObjectType string

const (
	ObjectTypeComment       ObjectType = "comment"
	ObjectTypeDeal          ObjectType = "deal"
	ObjectTypeEngagement    ObjectType = "engagement"
	ObjectTypeIdentity      ObjectType = "identity"
	ObjectTypeAiChatThread  ObjectType = "ai_chat_thread"
	ObjectTypeAiChatMessage ObjectType = "ai_chat_message"
	ObjectTypeDocument      ObjectType = "document"
	ObjectTypeAction        ObjectType = "action"
	ObjectTypeEvent         ObjectType = "event"
	ObjectTypeOrganization  ObjectType = "organization"
	ObjectTypeContact       ObjectType = "contact"
)

func (e ObjectType) ToPointer() *ObjectType {
	return &e
}
func (e *ObjectType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "comment":
		fallthrough
	case "deal":
		fallthrough
	case "engagement":
		fallthrough
	case "identity":
		fallthrough
	case "ai_chat_thread":
		fallthrough
	case "ai_chat_message":
		fallthrough
	case "document":
		fallthrough
	case "action":
		fallthrough
	case "event":
		fallthrough
	case "organization":
		fallthrough
	case "contact":
		*e = ObjectType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ObjectType: %v", v)
	}
}
