// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"openapi/internal/sdk/sdkinternal/utils"
)

type PrismObjectPropertiesExtended2 struct {
}

func (p PrismObjectPropertiesExtended2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PrismObjectPropertiesExtended2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

// #region class-body-prismobjectpropertiesextended2
// #endregion class-body-prismobjectpropertiesextended2

type PrismObjectPropertiesList2 struct {
}

func (p PrismObjectPropertiesList2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PrismObjectPropertiesList2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

// #region class-body-prismobjectpropertieslist2
// #endregion class-body-prismobjectpropertieslist2

type PrismObjectProperties2 struct {
	Extended *PrismObjectPropertiesExtended2 `json:"extended,omitzero"`
	// Properties keyed by property slug. Values can be strings, numbers, booleans, arrays, or null. For select/multiselect properties, values may be option slugs or option UUIDs on write; option slugs are returned on read.
	Default map[string]any             `json:"default,omitzero"`
	List    PrismObjectPropertiesList2 `json:"list"`
}

func (p PrismObjectProperties2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PrismObjectProperties2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PrismObjectProperties2) GetExtended() *PrismObjectPropertiesExtended2 {
	if p == nil {
		return nil
	}
	return p.Extended
}

func (p *PrismObjectProperties2) GetDefault() map[string]any {
	if p == nil {
		return nil
	}
	return p.Default
}

func (p *PrismObjectProperties2) GetList() PrismObjectPropertiesList2 {
	if p == nil {
		return PrismObjectPropertiesList2{}
	}
	return p.List
}

// #region class-body-prismobjectproperties2
// #endregion class-body-prismobjectproperties2

type PrismObjectPropertiesExtended1 struct {
}

func (p PrismObjectPropertiesExtended1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PrismObjectPropertiesExtended1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

// #region class-body-prismobjectpropertiesextended1
// #endregion class-body-prismobjectpropertiesextended1

type PrismObjectPropertiesList1 struct {
}

func (p PrismObjectPropertiesList1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PrismObjectPropertiesList1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

// #region class-body-prismobjectpropertieslist1
// #endregion class-body-prismobjectpropertieslist1

type PrismObjectProperties1 struct {
	Extended *PrismObjectPropertiesExtended1 `json:"extended,omitzero"`
	// Properties keyed by property slug. Values can be strings, numbers, booleans, arrays, or null. For select/multiselect properties, values may be option slugs or option UUIDs on write; option slugs are returned on read.
	Default map[string]any              `json:"default"`
	List    *PrismObjectPropertiesList1 `json:"list,omitzero"`
}

func (p PrismObjectProperties1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PrismObjectProperties1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PrismObjectProperties1) GetExtended() *PrismObjectPropertiesExtended1 {
	if p == nil {
		return nil
	}
	return p.Extended
}

func (p *PrismObjectProperties1) GetDefault() map[string]any {
	if p == nil {
		return map[string]any{}
	}
	return p.Default
}

func (p *PrismObjectProperties1) GetList() *PrismObjectPropertiesList1 {
	if p == nil {
		return nil
	}
	return p.List
}

// #region class-body-prismobjectproperties1
// #endregion class-body-prismobjectproperties1

type PrismObjectPropertiesUnionType string

const (
	PrismObjectPropertiesUnionTypePrismObjectProperties1 PrismObjectPropertiesUnionType = "PrismObjectProperties_1"
	PrismObjectPropertiesUnionTypePrismObjectProperties2 PrismObjectPropertiesUnionType = "PrismObjectProperties_2"
)

type PrismObjectPropertiesUnion struct {
	PrismObjectProperties1 *PrismObjectProperties1 `queryParam:"inline" union:"member"`
	PrismObjectProperties2 *PrismObjectProperties2 `queryParam:"inline" union:"member"`

	Type PrismObjectPropertiesUnionType
}

func CreatePrismObjectPropertiesUnionPrismObjectProperties1(prismObjectProperties1 PrismObjectProperties1) PrismObjectPropertiesUnion {
	typ := PrismObjectPropertiesUnionTypePrismObjectProperties1

	return PrismObjectPropertiesUnion{
		PrismObjectProperties1: &prismObjectProperties1,
		Type:                   typ,
	}
}

func CreatePrismObjectPropertiesUnionPrismObjectProperties2(prismObjectProperties2 PrismObjectProperties2) PrismObjectPropertiesUnion {
	typ := PrismObjectPropertiesUnionTypePrismObjectProperties2

	return PrismObjectPropertiesUnion{
		PrismObjectProperties2: &prismObjectProperties2,
		Type:                   typ,
	}
}

func (u *PrismObjectPropertiesUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var prismObjectProperties1 PrismObjectProperties1 = PrismObjectProperties1{}
	if err := utils.UnmarshalJSON(data, &prismObjectProperties1, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  PrismObjectPropertiesUnionTypePrismObjectProperties1,
			Value: &prismObjectProperties1,
		})
	}

	var prismObjectProperties2 PrismObjectProperties2 = PrismObjectProperties2{}
	if err := utils.UnmarshalJSON(data, &prismObjectProperties2, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  PrismObjectPropertiesUnionTypePrismObjectProperties2,
			Value: &prismObjectProperties2,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for PrismObjectPropertiesUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for PrismObjectPropertiesUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(PrismObjectPropertiesUnionType)
	switch best.Type {
	case PrismObjectPropertiesUnionTypePrismObjectProperties1:
		u.PrismObjectProperties1 = best.Value.(*PrismObjectProperties1)
		return nil
	case PrismObjectPropertiesUnionTypePrismObjectProperties2:
		u.PrismObjectProperties2 = best.Value.(*PrismObjectProperties2)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for PrismObjectPropertiesUnion", string(data))
}

func (u PrismObjectPropertiesUnion) MarshalJSON() ([]byte, error) {
	if u.PrismObjectProperties1 != nil {
		return utils.MarshalJSON(u.PrismObjectProperties1, "", true)
	}

	if u.PrismObjectProperties2 != nil {
		return utils.MarshalJSON(u.PrismObjectProperties2, "", true)
	}

	return nil, errors.New("could not marshal union type PrismObjectPropertiesUnion: all fields are null")
}
