// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/sdk/optionalnullable"
	"openapi/internal/sdk/sdkinternal/utils"
)

// PrismQueryRow - Row returned by the query endpoint. `id` is always present at the top level. Selected property values are returned under `properties`, keyed by property slug. Reference-typed values are returned as nested `{ id, properties }` objects.
type PrismQueryRow struct {
	ID string `json:"id"`
	// Selected property values keyed by property slug. For select/multiselect properties, option slugs are returned. For reference properties, values are nested `{ id, properties }` objects.
	Properties   map[string]any                              `json:"properties,omitzero"`
	IsUserObject *bool                                       `json:"is_user_object,omitzero"`
	Source       optionalnullable.OptionalNullable[[]string] `json:"source,omitzero"`
}

func (p PrismQueryRow) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PrismQueryRow) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PrismQueryRow) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PrismQueryRow) GetProperties() map[string]any {
	if p == nil {
		return nil
	}
	return p.Properties
}

func (p *PrismQueryRow) GetIsUserObject() *bool {
	if p == nil {
		return nil
	}
	return p.IsUserObject
}

func (p *PrismQueryRow) GetSource() optionalnullable.OptionalNullable[[]string] {
	if p == nil {
		return nil
	}
	return p.Source
}
