// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/sdk/sdkinternal/utils"
)

type PrismObjectResponseExtended struct {
}

type PrismObjectResponseList struct {
}

// PrismObjectResponse - Object returned by reads (get/create/patch/restore). id is always present.
type PrismObjectResponse struct {
	ID       string                       `json:"id"`
	Extended *PrismObjectResponseExtended `json:"extended,omitzero"`
	// Properties keyed by property slug.
	Default map[string]any           `json:"default,omitzero"`
	List    *PrismObjectResponseList `json:"list,omitzero"`
}

func (p PrismObjectResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PrismObjectResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PrismObjectResponse) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PrismObjectResponse) GetExtended() *PrismObjectResponseExtended {
	if p == nil {
		return nil
	}
	return p.Extended
}

func (p *PrismObjectResponse) GetDefault() map[string]any {
	if p == nil {
		return nil
	}
	return p.Default
}

func (p *PrismObjectResponse) GetList() *PrismObjectResponseList {
	if p == nil {
		return nil
	}
	return p.List
}
