// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/sdk/optionalnullable"
)

// PropertyOptionCreate - New option for a `select_str` or `multiselect_str` property. `type` identifies the per-type option table to write.
type PropertyOptionCreate struct {
	// Storage type for a property definition.
	Type PropertyType `json:"type"`
	// Scope the option to a specific list/app.
	ListID optionalnullable.OptionalNullable[string] `json:"list_id,omitzero"`
	// Display value for the option.
	Value string `json:"value"`
	// URL-safe identifier. Defaults to a slugified `value`.
	Slug        *string                                   `json:"slug,omitzero"`
	ColorScheme optionalnullable.OptionalNullable[string] `json:"color_scheme,omitzero"`
	SortIndex   optionalnullable.OptionalNullable[int64]  `json:"sort_index,omitzero"`
	Icon        optionalnullable.OptionalNullable[string] `json:"icon,omitzero"`
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	OptionGroup optionalnullable.OptionalNullable[string] `json:"option_group,omitzero"`
}

func (p *PropertyOptionCreate) GetType() PropertyType {
	if p == nil {
		return PropertyType("")
	}
	return p.Type
}

func (p *PropertyOptionCreate) GetListID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.ListID
}

func (p *PropertyOptionCreate) GetValue() string {
	if p == nil {
		return ""
	}
	return p.Value
}

func (p *PropertyOptionCreate) GetSlug() *string {
	if p == nil {
		return nil
	}
	return p.Slug
}

func (p *PropertyOptionCreate) GetColorScheme() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.ColorScheme
}

func (p *PropertyOptionCreate) GetSortIndex() optionalnullable.OptionalNullable[int64] {
	if p == nil {
		return nil
	}
	return p.SortIndex
}

func (p *PropertyOptionCreate) GetIcon() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Icon
}

func (p *PropertyOptionCreate) GetDescription() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PropertyOptionCreate) GetOptionGroup() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.OptionGroup
}
