// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/sdk/optionalnullable"
)

// PropertyOptionPatch - Partial update of a property option. `type` identifies the per-type option table to write.
type PropertyOptionPatch struct {
	// Storage type for a property definition.
	Type        PropertyType                              `json:"type"`
	ListID      optionalnullable.OptionalNullable[string] `json:"list_id,omitzero"`
	Value       *string                                   `json:"value,omitzero"`
	Slug        *string                                   `json:"slug,omitzero"`
	ColorScheme optionalnullable.OptionalNullable[string] `json:"color_scheme,omitzero"`
	SortIndex   optionalnullable.OptionalNullable[int64]  `json:"sort_index,omitzero"`
	Icon        optionalnullable.OptionalNullable[string] `json:"icon,omitzero"`
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	OptionGroup optionalnullable.OptionalNullable[string] `json:"option_group,omitzero"`
	Enabled     *bool                                     `json:"enabled,omitzero"`
}

func (p *PropertyOptionPatch) GetType() PropertyType {
	if p == nil {
		return PropertyType("")
	}
	return p.Type
}

func (p *PropertyOptionPatch) GetListID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.ListID
}

func (p *PropertyOptionPatch) GetValue() *string {
	if p == nil {
		return nil
	}
	return p.Value
}

func (p *PropertyOptionPatch) GetSlug() *string {
	if p == nil {
		return nil
	}
	return p.Slug
}

func (p *PropertyOptionPatch) GetColorScheme() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.ColorScheme
}

func (p *PropertyOptionPatch) GetSortIndex() optionalnullable.OptionalNullable[int64] {
	if p == nil {
		return nil
	}
	return p.SortIndex
}

func (p *PropertyOptionPatch) GetIcon() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Icon
}

func (p *PropertyOptionPatch) GetDescription() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PropertyOptionPatch) GetOptionGroup() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.OptionGroup
}

func (p *PropertyOptionPatch) GetEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.Enabled
}
