// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/sdk/optionalnullable"
	"openapi/internal/sdk/sdkinternal/utils"
)

type OptionObj struct {
	Value       string                                    `json:"value"`
	Slug        *string                                   `json:"slug,omitzero"`
	ColorScheme optionalnullable.OptionalNullable[string] `json:"color_scheme,omitzero"`
	SortIndex   optionalnullable.OptionalNullable[int64]  `json:"sort_index,omitzero"`
	Icon        optionalnullable.OptionalNullable[string] `json:"icon,omitzero"`
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	OptionGroup optionalnullable.OptionalNullable[string] `json:"option_group,omitzero"`
}

func (o *OptionObj) GetValue() string {
	if o == nil {
		return ""
	}
	return o.Value
}

func (o *OptionObj) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

func (o *OptionObj) GetColorScheme() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.ColorScheme
}

func (o *OptionObj) GetSortIndex() optionalnullable.OptionalNullable[int64] {
	if o == nil {
		return nil
	}
	return o.SortIndex
}

func (o *OptionObj) GetIcon() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Icon
}

func (o *OptionObj) GetDescription() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *OptionObj) GetOptionGroup() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.OptionGroup
}

// PropertyDefinitionCreate - New property definition. The definition is scoped to the calling team; pass `list_id` to scope it to a specific list as well. For `select_str`/`multiselect_str` types you may pre-seed choices via `options`.
type PropertyDefinitionCreate struct {
	// Storage type for a property definition.
	Type PropertyType `json:"type"`
	// Human-readable name. Must be unique within (team, list).
	Name string `json:"name"`
	// URL-safe identifier. Defaults to a slugified `name`. Disambiguated with a numeric suffix on conflict.
	Slug   *string                                   `json:"slug,omitzero"`
	Icon   optionalnullable.OptionalNullable[string] `json:"icon,omitzero"`
	ListID optionalnullable.OptionalNullable[string] `json:"list_id,omitzero"`
	// Only honored when `type` is `select_str` or `multiselect_str`.
	Options []OptionObj `json:"options,omitzero"`
}

func (p PropertyDefinitionCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PropertyDefinitionCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PropertyDefinitionCreate) GetType() PropertyType {
	if p == nil {
		return PropertyType("")
	}
	return p.Type
}

func (p *PropertyDefinitionCreate) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PropertyDefinitionCreate) GetSlug() *string {
	if p == nil {
		return nil
	}
	return p.Slug
}

func (p *PropertyDefinitionCreate) GetIcon() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Icon
}

func (p *PropertyDefinitionCreate) GetListID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.ListID
}

func (p *PropertyDefinitionCreate) GetOptions() []OptionObj {
	if p == nil {
		return nil
	}
	return p.Options
}
