// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/sdk/optionalnullable"
)

// PropertyOption - An enabled option for a select_str or multiselect_str property definition.
type PropertyOption struct {
	ID   string `json:"id"`
	Slug string `json:"slug"`
	// Display value for the option.
	Value       optionalnullable.OptionalNullable[string] `json:"value,omitzero"`
	ColorScheme optionalnullable.OptionalNullable[string] `json:"color_scheme,omitzero"`
	SortIndex   optionalnullable.OptionalNullable[int64]  `json:"sort_index,omitzero"`
	Icon        optionalnullable.OptionalNullable[string] `json:"icon,omitzero"`
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	OptionGroup optionalnullable.OptionalNullable[string] `json:"option_group,omitzero"`
}

func (p *PropertyOption) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PropertyOption) GetSlug() string {
	if p == nil {
		return ""
	}
	return p.Slug
}

func (p *PropertyOption) GetValue() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Value
}

func (p *PropertyOption) GetColorScheme() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.ColorScheme
}

func (p *PropertyOption) GetSortIndex() optionalnullable.OptionalNullable[int64] {
	if p == nil {
		return nil
	}
	return p.SortIndex
}

func (p *PropertyOption) GetIcon() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Icon
}

func (p *PropertyOption) GetDescription() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PropertyOption) GetOptionGroup() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.OptionGroup
}
