// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PropertyType - Storage type for a property definition.
type PropertyType string

const (
	PropertyTypeNum                      PropertyType = "num"
	PropertyTypeStr                      PropertyType = "str"
	PropertyTypeBool                     PropertyType = "bool"
	PropertyTypeDate                     PropertyType = "date"
	PropertyTypeText                     PropertyType = "text"
	PropertyTypeByte                     PropertyType = "byte"
	PropertyTypeSelectStr                PropertyType = "select_str"
	PropertyTypeMultiStr                 PropertyType = "multi_str"
	PropertyTypeMultiselectStr           PropertyType = "multiselect_str"
	PropertyTypeJsonb                    PropertyType = "jsonb"
	PropertyTypeRefIdentity              PropertyType = "ref_identity"
	PropertyTypeRefUser                  PropertyType = "ref_user"
	PropertyTypeRefOrganization          PropertyType = "ref_organization"
	PropertyTypeRefOrganizationUser      PropertyType = "ref_organization_user"
	PropertyTypeRefContact               PropertyType = "ref_contact"
	PropertyTypeRefThread                PropertyType = "ref_thread"
	PropertyTypeRefMessage               PropertyType = "ref_message"
	PropertyTypeRefEvent                 PropertyType = "ref_event"
	PropertyTypeRefAccount               PropertyType = "ref_account"
	PropertyTypeMultirefAiChatMessage    PropertyType = "multiref_ai_chat_message"
	PropertyTypeMultirefAction           PropertyType = "multiref_action"
	PropertyTypeMultirefContact          PropertyType = "multiref_contact"
	PropertyTypeMultirefLabel            PropertyType = "multiref_label"
	PropertyTypeMultirefThread           PropertyType = "multiref_thread"
	PropertyTypeMultirefMessages         PropertyType = "multiref_messages"
	PropertyTypeMultirefDocument         PropertyType = "multiref_document"
	PropertyTypeMultirefIdentity         PropertyType = "multiref_identity"
	PropertyTypeMultirefOrganization     PropertyType = "multiref_organization"
	PropertyTypeMultirefOrganizationUser PropertyType = "multiref_organization_user"
	PropertyTypeMultirefEngagement       PropertyType = "multiref_engagement"
	PropertyTypeMultirefAttendee         PropertyType = "multiref_attendee"
	PropertyTypeMultirefMeetingEntry     PropertyType = "multiref_meeting_entry"
	PropertyTypeMultirefReadReceipt      PropertyType = "multiref_read_receipt"
	PropertyTypeMultirefAccount          PropertyType = "multiref_account"
)

func (e PropertyType) ToPointer() *PropertyType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PropertyType) IsExact() bool {
	if e != nil {
		switch *e {
		case "num", "str", "bool", "date", "text", "byte", "select_str", "multi_str", "multiselect_str", "jsonb", "ref_identity", "ref_user", "ref_organization", "ref_organization_user", "ref_contact", "ref_thread", "ref_message", "ref_event", "ref_account", "multiref_ai_chat_message", "multiref_action", "multiref_contact", "multiref_label", "multiref_thread", "multiref_messages", "multiref_document", "multiref_identity", "multiref_organization", "multiref_organization_user", "multiref_engagement", "multiref_attendee", "multiref_meeting_entry", "multiref_read_receipt", "multiref_account":
			return true
		}
	}
	return false
}
