// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/sdk/optionalnullable"
	"openapi/internal/sdk/sdkinternal/utils"
)

// PropertyDefinition - Definition for a single property on an object type. Definitions with team_id and crm_id null are shared defaults; values may be scoped to a team and/or list (crm).
type PropertyDefinition struct {
	ID   string                                    `json:"id"`
	Slug string                                    `json:"slug"`
	Name optionalnullable.OptionalNullable[string] `json:"name,omitzero"`
	// Storage type for a property definition.
	Type   PropertyType                              `json:"type"`
	TeamID optionalnullable.OptionalNullable[string] `json:"team_id,omitzero"`
	// Identifier of the list this definition is scoped to, when applicable.
	CrmID optionalnullable.OptionalNullable[string] `json:"crm_id,omitzero"`
	// Present only for select_str and multiselect_str types.
	Options []PropertyOption `json:"options,omitzero"`
}

func (p PropertyDefinition) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PropertyDefinition) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PropertyDefinition) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PropertyDefinition) GetSlug() string {
	if p == nil {
		return ""
	}
	return p.Slug
}

func (p *PropertyDefinition) GetName() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *PropertyDefinition) GetType() PropertyType {
	if p == nil {
		return PropertyType("")
	}
	return p.Type
}

func (p *PropertyDefinition) GetTeamID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.TeamID
}

func (p *PropertyDefinition) GetCrmID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.CrmID
}

func (p *PropertyDefinition) GetOptions() []PropertyOption {
	if p == nil {
		return nil
	}
	return p.Options
}
