// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/sdk/optionalnullable"
)

// PropertyDefinitionPatch - Partial update of a property definition. Only `name`, `icon`, and `enabled` are editable. `type` identifies the per-type table to write.
type PropertyDefinitionPatch struct {
	// Storage type for a property definition.
	Type    PropertyType                              `json:"type"`
	ListID  optionalnullable.OptionalNullable[string] `json:"list_id,omitzero"`
	Name    *string                                   `json:"name,omitzero"`
	Icon    optionalnullable.OptionalNullable[string] `json:"icon,omitzero"`
	Enabled *bool                                     `json:"enabled,omitzero"`
}

func (p *PropertyDefinitionPatch) GetType() PropertyType {
	if p == nil {
		return PropertyType("")
	}
	return p.Type
}

func (p *PropertyDefinitionPatch) GetListID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.ListID
}

func (p *PropertyDefinitionPatch) GetName() *string {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *PropertyDefinitionPatch) GetIcon() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Icon
}

func (p *PropertyDefinitionPatch) GetEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.Enabled
}
