// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RecordOrderUpdate struct {
	ObjectIds []string `json:"object_ids"`
}

func (r *RecordOrderUpdate) GetObjectIds() []string {
	if r == nil {
		return []string{}
	}
	return r.ObjectIds
}
