// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"openapi/internal/sdk/optionalnullable"
	"openapi/internal/sdk/sdkinternal/utils"
)

type ViewBundleCombinator string

const (
	ViewBundleCombinatorAnd ViewBundleCombinator = "AND"
	ViewBundleCombinatorOr  ViewBundleCombinator = "OR"
)

func (e ViewBundleCombinator) ToPointer() *ViewBundleCombinator {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ViewBundleCombinator) IsExact() bool {
	if e != nil {
		switch *e {
		case "AND", "OR":
			return true
		}
	}
	return false
}

type ViewBundleGroupHiddenOptionIds struct {
}

func (v ViewBundleGroupHiddenOptionIds) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *ViewBundleGroupHiddenOptionIds) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

type ViewBundleGroupHiddenOptionIdsUnionType string

const (
	ViewBundleGroupHiddenOptionIdsUnionTypeArrayOfAny                     ViewBundleGroupHiddenOptionIdsUnionType = "arrayOfAny"
	ViewBundleGroupHiddenOptionIdsUnionTypeViewBundleGroupHiddenOptionIds ViewBundleGroupHiddenOptionIdsUnionType = "ViewBundle_group_hidden_option_ids"
	ViewBundleGroupHiddenOptionIdsUnionTypeUnknown                        ViewBundleGroupHiddenOptionIdsUnionType = "Unknown"
)

type ViewBundleGroupHiddenOptionIdsUnion struct {
	ArrayOfAny                     []any                           `queryParam:"inline" union:"member"`
	ViewBundleGroupHiddenOptionIds *ViewBundleGroupHiddenOptionIds `queryParam:"inline" union:"member"`
	UnknownRaw                     json.RawMessage                 `json:"-" union:"unknown"`

	Type ViewBundleGroupHiddenOptionIdsUnionType
}

func CreateViewBundleGroupHiddenOptionIdsUnionArrayOfAny(arrayOfAny []any) ViewBundleGroupHiddenOptionIdsUnion {
	typ := ViewBundleGroupHiddenOptionIdsUnionTypeArrayOfAny

	return ViewBundleGroupHiddenOptionIdsUnion{
		ArrayOfAny: arrayOfAny,
		Type:       typ,
	}
}

func CreateViewBundleGroupHiddenOptionIdsUnionViewBundleGroupHiddenOptionIds(viewBundleGroupHiddenOptionIds ViewBundleGroupHiddenOptionIds) ViewBundleGroupHiddenOptionIdsUnion {
	typ := ViewBundleGroupHiddenOptionIdsUnionTypeViewBundleGroupHiddenOptionIds

	return ViewBundleGroupHiddenOptionIdsUnion{
		ViewBundleGroupHiddenOptionIds: &viewBundleGroupHiddenOptionIds,
		Type:                           typ,
	}
}

func CreateViewBundleGroupHiddenOptionIdsUnionUnknown(raw json.RawMessage) ViewBundleGroupHiddenOptionIdsUnion {
	return ViewBundleGroupHiddenOptionIdsUnion{
		UnknownRaw: raw,
		Type:       ViewBundleGroupHiddenOptionIdsUnionTypeUnknown,
	}
}

func (u ViewBundleGroupHiddenOptionIdsUnion) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u ViewBundleGroupHiddenOptionIdsUnion) IsUnknown() bool {
	return u.Type == ViewBundleGroupHiddenOptionIdsUnionTypeUnknown
}

func (u *ViewBundleGroupHiddenOptionIdsUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var arrayOfAny []any = []any{}
	if err := utils.UnmarshalJSON(data, &arrayOfAny, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ViewBundleGroupHiddenOptionIdsUnionTypeArrayOfAny,
			Value: arrayOfAny,
		})
	}

	var viewBundleGroupHiddenOptionIds ViewBundleGroupHiddenOptionIds = ViewBundleGroupHiddenOptionIds{}
	if err := utils.UnmarshalJSON(data, &viewBundleGroupHiddenOptionIds, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ViewBundleGroupHiddenOptionIdsUnionTypeViewBundleGroupHiddenOptionIds,
			Value: &viewBundleGroupHiddenOptionIds,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ViewBundleGroupHiddenOptionIdsUnionTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ViewBundleGroupHiddenOptionIdsUnionTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ViewBundleGroupHiddenOptionIdsUnionType)
	switch best.Type {
	case ViewBundleGroupHiddenOptionIdsUnionTypeArrayOfAny:
		u.ArrayOfAny = best.Value.([]any)
		return nil
	case ViewBundleGroupHiddenOptionIdsUnionTypeViewBundleGroupHiddenOptionIds:
		u.ViewBundleGroupHiddenOptionIds = best.Value.(*ViewBundleGroupHiddenOptionIds)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = ViewBundleGroupHiddenOptionIdsUnionTypeUnknown
	return nil
}

func (u ViewBundleGroupHiddenOptionIdsUnion) MarshalJSON() ([]byte, error) {
	if u.ArrayOfAny != nil {
		return utils.MarshalJSON(u.ArrayOfAny, "", true)
	}

	if u.ViewBundleGroupHiddenOptionIds != nil {
		return utils.MarshalJSON(u.ViewBundleGroupHiddenOptionIds, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type ViewBundleGroupHiddenOptionIdsUnion: all fields are null")
}

// ViewBundle - A view (saved configuration for displaying records of a given object type) plus its select/filter/sort children. Properties in select/filter/sort are referenced by slug.
type ViewBundle struct {
	ID           *string                                           `json:"id,omitzero"`
	TeamID       optionalnullable.OptionalNullable[string]         `json:"team_id,omitzero"`
	ListID       optionalnullable.OptionalNullable[string]         `json:"list_id,omitzero"`
	UserID       optionalnullable.OptionalNullable[string]         `json:"user_id,omitzero"`
	Name         string                                            `json:"name"`
	Icon         optionalnullable.OptionalNullable[string]         `json:"icon,omitzero"`
	ViewType     string                                            `json:"view_type"`
	Combinator   *ViewBundleCombinator                             `json:"combinator,omitzero"`
	SortOrder    optionalnullable.OptionalNullable[int64]          `json:"sort_order,omitzero"`
	ColumnLayout optionalnullable.OptionalNullable[map[string]any] `json:"column_layout,omitzero"`
	// Property slug to group by
	GroupBy              optionalnullable.OptionalNullable[string]                              `json:"group_by,omitzero"`
	GroupSort            optionalnullable.OptionalNullable[string]                              `json:"group_sort,omitzero"`
	GroupHideEmpty       optionalnullable.OptionalNullable[bool]                                `json:"group_hide_empty,omitzero"`
	GroupHiddenOptionIds optionalnullable.OptionalNullable[ViewBundleGroupHiddenOptionIdsUnion] `json:"group_hidden_option_ids,omitzero"`
	AggregationType      optionalnullable.OptionalNullable[string]                              `json:"aggregation_type,omitzero"`
	AggregationPropDefID optionalnullable.OptionalNullable[string]                              `json:"aggregation_prop_def_id,omitzero"`
	// Property slugs (dot-paths permitted for refs)
	Select []string `json:"select,omitzero"`
	// Each entry is { slug: { comparator: value } }
	Filter []map[string]any `json:"filter,omitzero"`
	// Each entry is { slug: 'asc' | 'desc' }
	Sort      []map[string]any                          `json:"sort,omitzero"`
	CreatedAt *string                                   `json:"created_at,omitzero"`
	UpdatedAt optionalnullable.OptionalNullable[string] `json:"updated_at,omitzero"`
}

func (v ViewBundle) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *ViewBundle) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *ViewBundle) GetID() *string {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *ViewBundle) GetTeamID() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.TeamID
}

func (v *ViewBundle) GetListID() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.ListID
}

func (v *ViewBundle) GetUserID() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.UserID
}

func (v *ViewBundle) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *ViewBundle) GetIcon() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.Icon
}

func (v *ViewBundle) GetViewType() string {
	if v == nil {
		return ""
	}
	return v.ViewType
}

func (v *ViewBundle) GetCombinator() *ViewBundleCombinator {
	if v == nil {
		return nil
	}
	return v.Combinator
}

func (v *ViewBundle) GetSortOrder() optionalnullable.OptionalNullable[int64] {
	if v == nil {
		return nil
	}
	return v.SortOrder
}

func (v *ViewBundle) GetColumnLayout() optionalnullable.OptionalNullable[map[string]any] {
	if v == nil {
		return nil
	}
	return v.ColumnLayout
}

func (v *ViewBundle) GetGroupBy() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.GroupBy
}

func (v *ViewBundle) GetGroupSort() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.GroupSort
}

func (v *ViewBundle) GetGroupHideEmpty() optionalnullable.OptionalNullable[bool] {
	if v == nil {
		return nil
	}
	return v.GroupHideEmpty
}

func (v *ViewBundle) GetGroupHiddenOptionIds() optionalnullable.OptionalNullable[ViewBundleGroupHiddenOptionIdsUnion] {
	if v == nil {
		return nil
	}
	return v.GroupHiddenOptionIds
}

func (v *ViewBundle) GetAggregationType() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.AggregationType
}

func (v *ViewBundle) GetAggregationPropDefID() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.AggregationPropDefID
}

func (v *ViewBundle) GetSelect() []string {
	if v == nil {
		return nil
	}
	return v.Select
}

func (v *ViewBundle) GetFilter() []map[string]any {
	if v == nil {
		return nil
	}
	return v.Filter
}

func (v *ViewBundle) GetSort() []map[string]any {
	if v == nil {
		return nil
	}
	return v.Sort
}

func (v *ViewBundle) GetCreatedAt() *string {
	if v == nil {
		return nil
	}
	return v.CreatedAt
}

func (v *ViewBundle) GetUpdatedAt() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.UpdatedAt
}
