// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"openapi/internal/sdk/optionalnullable"
	"openapi/internal/sdk/sdkinternal/utils"
)

type ViewBundlePatchCombinator string

const (
	ViewBundlePatchCombinatorAnd ViewBundlePatchCombinator = "AND"
	ViewBundlePatchCombinatorOr  ViewBundlePatchCombinator = "OR"
)

func (e ViewBundlePatchCombinator) ToPointer() *ViewBundlePatchCombinator {
	return &e
}
func (e *ViewBundlePatchCombinator) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "AND":
		fallthrough
	case "OR":
		*e = ViewBundlePatchCombinator(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ViewBundlePatchCombinator: %v", v)
	}
}

type ViewBundlePatchGroupHiddenOptionIds struct {
}

func (v ViewBundlePatchGroupHiddenOptionIds) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *ViewBundlePatchGroupHiddenOptionIds) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

type ViewBundlePatchGroupHiddenOptionIdsUnionType string

const (
	ViewBundlePatchGroupHiddenOptionIdsUnionTypeArrayOfAny                          ViewBundlePatchGroupHiddenOptionIdsUnionType = "arrayOfAny"
	ViewBundlePatchGroupHiddenOptionIdsUnionTypeViewBundlePatchGroupHiddenOptionIds ViewBundlePatchGroupHiddenOptionIdsUnionType = "ViewBundlePatch_group_hidden_option_ids"
)

type ViewBundlePatchGroupHiddenOptionIdsUnion struct {
	ArrayOfAny                          []any                                `queryParam:"inline" union:"member"`
	ViewBundlePatchGroupHiddenOptionIds *ViewBundlePatchGroupHiddenOptionIds `queryParam:"inline" union:"member"`

	Type ViewBundlePatchGroupHiddenOptionIdsUnionType
}

func CreateViewBundlePatchGroupHiddenOptionIdsUnionArrayOfAny(arrayOfAny []any) ViewBundlePatchGroupHiddenOptionIdsUnion {
	typ := ViewBundlePatchGroupHiddenOptionIdsUnionTypeArrayOfAny

	return ViewBundlePatchGroupHiddenOptionIdsUnion{
		ArrayOfAny: arrayOfAny,
		Type:       typ,
	}
}

func CreateViewBundlePatchGroupHiddenOptionIdsUnionViewBundlePatchGroupHiddenOptionIds(viewBundlePatchGroupHiddenOptionIds ViewBundlePatchGroupHiddenOptionIds) ViewBundlePatchGroupHiddenOptionIdsUnion {
	typ := ViewBundlePatchGroupHiddenOptionIdsUnionTypeViewBundlePatchGroupHiddenOptionIds

	return ViewBundlePatchGroupHiddenOptionIdsUnion{
		ViewBundlePatchGroupHiddenOptionIds: &viewBundlePatchGroupHiddenOptionIds,
		Type:                                typ,
	}
}

func (u *ViewBundlePatchGroupHiddenOptionIdsUnion) UnmarshalJSON(data []byte) (err error) {
	previous := *u
	*u = ViewBundlePatchGroupHiddenOptionIdsUnion{}
	defer func() {
		if err != nil {
			*u = previous
		}
	}()

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var arrayOfAny []any = []any{}
	if err := utils.UnmarshalJSON(data, &arrayOfAny, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ViewBundlePatchGroupHiddenOptionIdsUnionTypeArrayOfAny,
			Value: arrayOfAny,
		})
	}

	var viewBundlePatchGroupHiddenOptionIds ViewBundlePatchGroupHiddenOptionIds = ViewBundlePatchGroupHiddenOptionIds{}
	if err := utils.UnmarshalJSON(data, &viewBundlePatchGroupHiddenOptionIds, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ViewBundlePatchGroupHiddenOptionIdsUnionTypeViewBundlePatchGroupHiddenOptionIds,
			Value: &viewBundlePatchGroupHiddenOptionIds,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ViewBundlePatchGroupHiddenOptionIdsUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ViewBundlePatchGroupHiddenOptionIdsUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ViewBundlePatchGroupHiddenOptionIdsUnionType)
	switch best.Type {
	case ViewBundlePatchGroupHiddenOptionIdsUnionTypeArrayOfAny:
		u.ArrayOfAny = best.Value.([]any)
		return nil
	case ViewBundlePatchGroupHiddenOptionIdsUnionTypeViewBundlePatchGroupHiddenOptionIds:
		u.ViewBundlePatchGroupHiddenOptionIds = best.Value.(*ViewBundlePatchGroupHiddenOptionIds)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ViewBundlePatchGroupHiddenOptionIdsUnion", string(data))
}

func (u ViewBundlePatchGroupHiddenOptionIdsUnion) MarshalJSON() ([]byte, error) {
	if u.ArrayOfAny != nil {
		return utils.MarshalJSON(u.ArrayOfAny, "", true)
	}

	if u.ViewBundlePatchGroupHiddenOptionIds != nil {
		return utils.MarshalJSON(u.ViewBundlePatchGroupHiddenOptionIds, "", true)
	}

	return nil, errors.New("could not marshal union type ViewBundlePatchGroupHiddenOptionIdsUnion: all fields are null")
}

// ViewBundlePatch - Partial update. Any of select/filter/sort, when present, replaces that group wholesale.
type ViewBundlePatch struct {
	Name                 *string                                                                     `json:"name,omitzero"`
	Icon                 optionalnullable.OptionalNullable[string]                                   `json:"icon,omitzero"`
	ViewType             *string                                                                     `json:"view_type,omitzero"`
	Combinator           *ViewBundlePatchCombinator                                                  `json:"combinator,omitzero"`
	SortOrder            optionalnullable.OptionalNullable[int64]                                    `json:"sort_order,omitzero"`
	ColumnLayout         optionalnullable.OptionalNullable[map[string]any]                           `json:"column_layout,omitzero"`
	TeamID               optionalnullable.OptionalNullable[string]                                   `json:"team_id,omitzero"`
	ListID               optionalnullable.OptionalNullable[string]                                   `json:"list_id,omitzero"`
	UserID               optionalnullable.OptionalNullable[string]                                   `json:"user_id,omitzero"`
	GroupBy              optionalnullable.OptionalNullable[string]                                   `json:"group_by,omitzero"`
	GroupSort            optionalnullable.OptionalNullable[string]                                   `json:"group_sort,omitzero"`
	GroupHideEmpty       optionalnullable.OptionalNullable[bool]                                     `json:"group_hide_empty,omitzero"`
	GroupHiddenOptionIds optionalnullable.OptionalNullable[ViewBundlePatchGroupHiddenOptionIdsUnion] `json:"group_hidden_option_ids,omitzero"`
	AggregationType      optionalnullable.OptionalNullable[string]                                   `json:"aggregation_type,omitzero"`
	AggregationPropDefID optionalnullable.OptionalNullable[string]                                   `json:"aggregation_prop_def_id,omitzero"`
	Select               []string                                                                    `json:"select,omitzero"`
	Filter               []map[string]any                                                            `json:"filter,omitzero"`
	Sort                 []map[string]any                                                            `json:"sort,omitzero"`
}

func (v ViewBundlePatch) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *ViewBundlePatch) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *ViewBundlePatch) GetName() *string {
	if v == nil {
		return nil
	}
	return v.Name
}

func (v *ViewBundlePatch) GetIcon() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.Icon
}

func (v *ViewBundlePatch) GetViewType() *string {
	if v == nil {
		return nil
	}
	return v.ViewType
}

func (v *ViewBundlePatch) GetCombinator() *ViewBundlePatchCombinator {
	if v == nil {
		return nil
	}
	return v.Combinator
}

func (v *ViewBundlePatch) GetSortOrder() optionalnullable.OptionalNullable[int64] {
	if v == nil {
		return nil
	}
	return v.SortOrder
}

func (v *ViewBundlePatch) GetColumnLayout() optionalnullable.OptionalNullable[map[string]any] {
	if v == nil {
		return nil
	}
	return v.ColumnLayout
}

func (v *ViewBundlePatch) GetTeamID() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.TeamID
}

func (v *ViewBundlePatch) GetListID() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.ListID
}

func (v *ViewBundlePatch) GetUserID() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.UserID
}

func (v *ViewBundlePatch) GetGroupBy() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.GroupBy
}

func (v *ViewBundlePatch) GetGroupSort() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.GroupSort
}

func (v *ViewBundlePatch) GetGroupHideEmpty() optionalnullable.OptionalNullable[bool] {
	if v == nil {
		return nil
	}
	return v.GroupHideEmpty
}

func (v *ViewBundlePatch) GetGroupHiddenOptionIds() optionalnullable.OptionalNullable[ViewBundlePatchGroupHiddenOptionIdsUnion] {
	if v == nil {
		return nil
	}
	return v.GroupHiddenOptionIds
}

func (v *ViewBundlePatch) GetAggregationType() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.AggregationType
}

func (v *ViewBundlePatch) GetAggregationPropDefID() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.AggregationPropDefID
}

func (v *ViewBundlePatch) GetSelect() []string {
	if v == nil {
		return nil
	}
	return v.Select
}

func (v *ViewBundlePatch) GetFilter() []map[string]any {
	if v == nil {
		return nil
	}
	return v.Filter
}

func (v *ViewBundlePatch) GetSort() []map[string]any {
	if v == nil {
		return nil
	}
	return v.Sort
}
