// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/sdk/optionalnullable"
	"openapi/internal/sdk/sdkinternal/utils"
)

type Records struct {
	Data       []map[string]any                          `json:"data"`
	HasMore    bool                                      `json:"has_more"`
	NextCursor optionalnullable.OptionalNullable[string] `json:"next_cursor,omitzero"`
}

func (r Records) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *Records) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *Records) GetData() []map[string]any {
	if r == nil {
		return []map[string]any{}
	}
	return r.Data
}

func (r *Records) GetHasMore() bool {
	if r == nil {
		return false
	}
	return r.HasMore
}

func (r *Records) GetNextCursor() optionalnullable.OptionalNullable[string] {
	if r == nil {
		return nil
	}
	return r.NextCursor
}

// ViewBundleWithRecords - Returned by `GET /views/{viewId}?include=records`. Same `records` shape as the standalone list-view-records endpoint.
type ViewBundleWithRecords struct {
	// A view (saved configuration for displaying records of a given object type) plus its select/filter/sort children. Properties in select/filter/sort are referenced by slug.
	View    ViewBundle `json:"view"`
	Records Records    `json:"records"`
}

func (v ViewBundleWithRecords) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *ViewBundleWithRecords) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *ViewBundleWithRecords) GetView() ViewBundle {
	if v == nil {
		return ViewBundle{}
	}
	return v.View
}

func (v *ViewBundleWithRecords) GetRecords() Records {
	if v == nil {
		return Records{}
	}
	return v.Records
}
