// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ViewObjectType string

const (
	ViewObjectTypeComment      ViewObjectType = "comment"
	ViewObjectTypeAction       ViewObjectType = "action"
	ViewObjectTypeDeal         ViewObjectType = "deal"
	ViewObjectTypeEngagement   ViewObjectType = "engagement"
	ViewObjectTypeDocument     ViewObjectType = "document"
	ViewObjectTypeEvent        ViewObjectType = "event"
	ViewObjectTypeIdentity     ViewObjectType = "identity"
	ViewObjectTypeOrganization ViewObjectType = "organization"
)

func (e ViewObjectType) ToPointer() *ViewObjectType {
	return &e
}
func (e *ViewObjectType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "comment":
		fallthrough
	case "action":
		fallthrough
	case "deal":
		fallthrough
	case "engagement":
		fallthrough
	case "document":
		fallthrough
	case "event":
		fallthrough
	case "identity":
		fallthrough
	case "organization":
		*e = ViewObjectType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ViewObjectType: %v", v)
	}
}
